/**
 * Seed demo login credentials for every role into MongoDB (`users` collection)
 * using `server/.env` (MONGODB_URI), and export docs copies for QA.
 *
 * Usage (from repo root):
 *   npm run seed:credentials
 *   npx tsx client/scripts/seed-demo-credentials.ts
 *
 * Options:
 *   --docs-only   Skip Mongo; only write docs/*
 *   --mongo-only  Skip docs; only upsert Mongo users
 */

import { createRequire } from "node:module";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  DEMO_USERS,
  DEMO_USERS_HIDDEN,
  ROLE_LABELS,
  type DemoUser,
} from "../lib/auth";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "../..");
const outDir = join(repoRoot, "docs");
const serverRoot = join(repoRoot, "server");
const require = createRequire(join(serverRoot, "package.json"));

type CredentialRow = DemoUser & {
  visibleOnLogin: boolean;
  roleLabel: string;
  plant: string;
};

function plantOf(u: DemoUser): string {
  if (!u.siteId) return "org-wide";
  if (u.siteId === "s-etp") return "ETP";
  if (u.siteId === "s-ro") return "RO";
  if (u.siteId === "s-mee") return "MEE";
  return u.siteId;
}

function rows(): CredentialRow[] {
  const visible = DEMO_USERS.map((u) => ({
    ...u,
    visibleOnLogin: true,
    roleLabel: ROLE_LABELS[u.role],
    plant: plantOf(u),
  }));
  const hidden = DEMO_USERS_HIDDEN.map((u) => ({
    ...u,
    visibleOnLogin: false,
    roleLabel: ROLE_LABELS[u.role],
    plant: plantOf(u),
  }));
  return [...visible, ...hidden];
}

function toCsv(data: CredentialRow[]): string {
  const header = [
    "email",
    "password",
    "name",
    "role",
    "roleLabel",
    "plant",
    "siteId",
    "employeeId",
    "visibleOnLogin",
  ];
  const escape = (v: string) => `"${String(v).replaceAll('"', '""')}"`;
  const lines = data.map((r) =>
    [
      r.email,
      r.password,
      r.name,
      r.role,
      r.roleLabel,
      r.plant,
      r.siteId ?? "",
      r.employeeId ?? "",
      r.visibleOnLogin ? "yes" : "no",
    ]
      .map(escape)
      .join(","),
  );
  return [header.join(","), ...lines].join("\n") + "\n";
}

function toMarkdown(data: CredentialRow[]): string {
  const byRole = new Map<string, CredentialRow[]>();
  for (const r of data) {
    const key = r.roleLabel;
    const list = byRole.get(key) ?? [];
    list.push(r);
    byRole.set(key, list);
  }

  const lines: string[] = [
    "# Demo credentials (every role)",
    "",
    "Generated by `client/scripts/seed-demo-credentials.ts`.",
    "",
    "**Shared password for all accounts:** `nectar2026`",
    "",
    "Roster / gap “today” for demos: **2026-09-23**",
    "",
    "MongoDB collection: **`users`** (db `nectar_enviro`, via `server/.env` → `MONGODB_URI`)",
    "",
    "## Quick matrix (one account per role · plant)",
    "",
    "| Role | Plant | Email | Password |",
    "| --- | --- | --- | --- |",
  ];

  const quick: Array<[string, string, string]> = [
    ["Director", "org-wide", "director@nectarenviro.com"],
    ["HR Manager", "org-wide", "hr@nectarenviro.com"],
    ["Manager", "ETP", "etp.manager@nectarenviro.com"],
    ["Manager", "RO", "ro.manager@nectarenviro.com"],
    ["Manager", "MEE", "mee.manager@nectarenviro.com"],
    ["Shift In-Charge", "ETP", "etp.shift@nectarenviro.com"],
    ["Shift In-Charge", "RO", "ro.shift@nectarenviro.com"],
    ["Shift In-Charge", "MEE", "mee.shift@nectarenviro.com"],
    ["Supervisor", "ETP", "etp.supervisor@nectarenviro.com"],
    ["Supervisor", "RO", "ro.supervisor@nectarenviro.com"],
    ["Supervisor", "MEE", "mee.supervisor@nectarenviro.com"],
    ["Employee", "ETP", "shilpa.hotkar@nectarenviro.com"],
    ["Employee", "RO", "rafik.shaikh@nectarenviro.com"],
    ["Employee", "MEE", "abhinandan.pawane@nectarenviro.com"],
    ["Site In-Charge (hidden)", "ETP", "site@nectarenviro.com"],
    ["Safety In-Charge (hidden)", "ETP", "safety@nectarenviro.com"],
  ];

  for (const [role, plant, email] of quick) {
    lines.push(`| ${role} | ${plant} | \`${email}\` | \`nectar2026\` |`);
  }

  lines.push("", "## Full account list", "");

  for (const [roleLabel, list] of byRole) {
    lines.push(`### ${roleLabel}`, "");
    lines.push("| Email | Name | Plant | Visible on login |");
    lines.push("| --- | --- | --- | --- |");
    for (const r of list) {
      lines.push(
        `| \`${r.email}\` | ${r.name} | ${r.plant} | ${r.visibleOnLogin ? "yes" : "hidden"} |`,
      );
    }
    lines.push("");
  }

  lines.push(
    "## Notes",
    "",
    "- Client login still uses `client/lib/auth.ts` for the demo UI.",
    "- This script upserts the same accounts into MongoDB `users` for API / future auth.",
    "- Passwords are stored as demo plaintext — hash before production.",
    "- Hidden accounts work if typed manually on the login form.",
    "",
  );

  return lines.join("\n");
}

function writeDocs(data: CredentialRow[]) {
  mkdirSync(outDir, { recursive: true });
  const jsonPath = join(outDir, "demo-credentials.json");
  const csvPath = join(outDir, "demo-credentials.csv");
  const mdPath = join(outDir, "demo-credentials.md");

  writeFileSync(
    jsonPath,
    JSON.stringify(
      {
        generatedAt: new Date().toISOString(),
        sharedPassword: "nectar2026",
        rosterToday: "2026-09-23",
        mongoCollection: "users",
        count: data.length,
        accounts: data,
      },
      null,
      2,
    ) + "\n",
    "utf8",
  );
  writeFileSync(csvPath, toCsv(data), "utf8");
  writeFileSync(mdPath, toMarkdown(data), "utf8");

  console.log(`Docs written (${data.length} accounts):`);
  console.log(`  ${jsonPath}`);
  console.log(`  ${csvPath}`);
  console.log(`  ${mdPath}`);
}

async function seedMongo(data: CredentialRow[]) {
  const dotenv = require("dotenv") as typeof import("dotenv");
  const mongoose = require("mongoose") as typeof import("mongoose");

  dotenv.config({ path: join(serverRoot, ".env") });

  const uri = process.env.MONGODB_URI;
  if (!uri) {
    throw new Error(
      "MONGODB_URI missing. Set it in server/.env (see Atlas connection string).",
    );
  }

  const redacted = uri.replace(/:([^:@]+)@/, ":****@");
  console.log(`Connecting to MongoDB: ${redacted}`);

  await mongoose.connect(uri, { dbName: "nectar_enviro" });

  const UserSchema = new mongoose.Schema(
    {
      email: { type: String, required: true, unique: true, lowercase: true },
      password: { type: String, required: true },
      name: { type: String, required: true },
      role: { type: String, required: true },
      siteId: String,
      employeeId: String,
      visibleOnLogin: { type: Boolean, default: true },
      active: { type: Boolean, default: true },
    },
    { collection: "users", timestamps: true },
  );

  const UserModel =
    mongoose.models.User ?? mongoose.model("User", UserSchema, "users");

  let upserted = 0;
  for (const row of data) {
    await UserModel.findOneAndUpdate(
      { email: row.email.toLowerCase() },
      {
        $set: {
          email: row.email.toLowerCase(),
          password: row.password,
          name: row.name,
          role: row.role,
          siteId: row.siteId,
          employeeId: row.employeeId,
          visibleOnLogin: row.visibleOnLogin,
          active: true,
        },
      },
      { upsert: true, new: true },
    );
    upserted += 1;
  }

  const total = await UserModel.countDocuments({});
  console.log(`Mongo upserted ${upserted} accounts into nectar_enviro.users (total now ${total}).`);

  await mongoose.disconnect();
}

async function main() {
  const args = new Set(process.argv.slice(2));
  const docsOnly = args.has("--docs-only");
  const mongoOnly = args.has("--mongo-only");
  const data = rows();

  if (!mongoOnly) {
    writeDocs(data);
    console.log("");
  }

  if (!docsOnly) {
    try {
      await seedMongo(data);
    } catch (err) {
      console.error("Mongo seed failed:", err instanceof Error ? err.message : err);
      process.exitCode = 1;
      return;
    }
  }

  console.log("");
  console.log("Shared password: nectar2026");
  console.table(
    data
      .filter((r) => r.visibleOnLogin)
      .map((r) => ({
        role: r.roleLabel,
        plant: r.plant,
        email: r.email,
        password: r.password,
      })),
  );
}

main();
