export const coursesSeed = [
  // =========================================================================
  // 1. EFFLUENT TREATMENT PLANTS (ETP) - 5 COURSES
  // =========================================================================
  {
    id: 'course-etp-101',
    courseId: 'course-etp-101',
    code: 'ETP-101',
    title: 'ETP Biological & Chemical Treatment Operations',
    section: 'Effluent Treatment Plants (ETP)',
    category: 'Effluent Treatment Plants (ETP)',
    department: 'ETP Operations',
    jobCategoryId: 'jc-etp-op',
    description:
      'Comprehensive industrial effluent operations: equalization air sparging, coagulant jar testing, primary settling, aerobic biological flocs, and clarifier sludge recycling.',
    thumbnailUrl: '/courses/etp_plant.jpg',
    provider: 'Nectar Technical Operations',
    rating: 4.9,
    reviewCount: 42,
    level: 'Intermediate',
    estimatedHours: 4.5,
    passThreshold: 70,
    modules: [
      {
        id: 'mod-etp-101-aeration',
        moduleId: 'mod-etp-101-aeration',
        order: 1,
        title: 'Aeration Basin Dynamics & DO Stabilization',
        description: 'Dissolved oxygen monitoring (2.0-3.0 ppm), diffuser grid aeration efficiency, and blower tuning.',
        videos: [
          {
            id: 'vid-etp-101-aer-01',
            videoId: 'vid-etp-101-aer-01',
            order: 1,
            title: 'Aeration Tank Hydraulics & DO Micro-Sensors',
            durationMinutes: 1,
            videoUrl: '/videos/etp-aeration-intro.mp4',
            description: 'Optical DO probe calibration and diurnal oxygen consumption patterns under heavy industrial loading.',
          },
          {
            id: 'vid-etp-101-aer-02',
            videoId: 'vid-etp-101-aer-02',
            order: 2,
            title: 'Fine Bubble Diffuser Maintenance & Delta-P',
            durationMinutes: 1,
            videoUrl: '/videos/etp-diffuser-cleaning.mp4',
            description: 'Acid wash cleaning of EPDM diffusers and header pressure relief valve inspection.',
          },
        ],
      },
      {
        id: 'mod-etp-101-clarifier',
        moduleId: 'mod-etp-101-clarifier',
        order: 2,
        title: 'Secondary Clarifier Settling & Sludge Blanket Profiling',
        description: 'Sludge blanket depth measurement, RAS flow rate regulation, and weir overflow trough cleansing.',
        videos: [
          {
            id: 'vid-etp-101-clar-01',
            videoId: 'vid-etp-101-clar-01',
            order: 1,
            title: 'Sludge Blanket Core Sampling (Judge Tool)',
            durationMinutes: 1,
            videoUrl: '/videos/etp-sludge-judge.mp4',
            description: 'Accurate blanket level tracking to prevent pin-point floc carryover over effluent weirs.',
          },
          {
            id: 'vid-etp-101-clar-02',
            videoId: 'vid-etp-101-clar-02',
            order: 2,
            title: 'RAS/WAS Pumping Ratios & Scraper Bridge Checks',
            durationMinutes: 1,
            videoUrl: '/videos/etp-ras-pumps.mp4',
            description: 'Centrifugal RAS pump priming, torque overload alarms, and skimmer arm alignment.',
          },
        ],
      },
      {
        id: 'mod-etp-101-compliance',
        moduleId: 'mod-etp-101-compliance',
        order: 3,
        title: 'Effluent Quality Testing & COD/BOD Mass Balance',
        description: 'Standard spectrophotometric COD digestions, 3-day BOD5 incubator assays, and SPCB discharge log compliance.',
        videos: [
          {
            id: 'vid-etp-101-comp-01',
            videoId: 'vid-etp-101-comp-01',
            order: 1,
            title: 'Closed Reflux Spectrophotometric COD Digestions',
            durationMinutes: 1,
            videoUrl: '/videos/etp-cod-testing.mp4',
            description: 'Potassium dichromate digest block protocols and colorimetric titrations for treated effluent.',
          },
        ],
      },
    ],
    abilities: [
      {
        id: 'ab-1-1',
        courseId: 'course-etp-101',
        order: 1,
        code: '1.1',
        title: 'Process Flow & Design Hydraulic Retention Time (HRT)',
        description: 'Understanding plant inlet screening, equalization tank buffer volume, and peak flow shock load absorption.',
        videoDurationMinutes: 1,
        competencyAreaId: 'ca-etp-bio',
      },
      {
        id: 'ab-1-2',
        courseId: 'course-etp-101',
        order: 2,
        code: '1.2',
        title: 'Coagulation & Jar Test Chemical Dosage',
        description: 'Bench-scale jar testing to optimize alum, lime, and polyelectrolyte dosing for varying influent turbidity.',
        videoDurationMinutes: 1,
        competencyAreaId: 'ca-etp-chem',
      },
      {
        id: 'ab-1-3',
        courseId: 'course-etp-101',
        order: 3,
        code: '1.3',
        title: 'Aeration Basin DO & Mixed Liquor Suspended Solids (MLSS)',
        description: 'Maintaining active biomass health, dissolved oxygen between 2.0-3.0 mg/L, and Food-to-Microorganism (F/M) balance.',
        videoDurationMinutes: 1,
        competencyAreaId: 'ca-etp-bio',
      },
    ],
  },
  {
    id: 'course-etp-102',
    courseId: 'course-etp-102',
    code: 'ETP-102',
    title: 'Equalization, Flash Mixing & Chemical Jar Testing',
    section: 'Effluent Treatment Plants (ETP)',
    category: 'Effluent Treatment Plants (ETP)',
    department: 'ETP Operations',
    jobCategoryId: 'jc-etp-op',
    description:
      'Chemical precipitation stoichiometry: optimizing coagulant dosing (alum, polyaluminium chloride, ferric chloride) and polymeric flocculants using laboratory jar test rigs.',
    thumbnailUrl: '/courses/jar_test_floc.jpg',
    provider: 'Nectar Technical Operations',
    rating: 4.8,
    reviewCount: 31,
    level: 'Foundation',
    estimatedHours: 3.5,
    passThreshold: 70,
    modules: [
      {
        id: 'mod-etp-102-eq',
        moduleId: 'mod-etp-102-eq',
        order: 1,
        title: 'Equalization Basin Homogenization & pH Trimming',
        description: 'Air agitation spargers, submersible mixer placement, and dual acid/caustic auto-dosing loops.',
        videos: [
          {
            id: 'vid-etp-102-eq-01',
            videoId: 'vid-etp-102-eq-01',
            order: 1,
            title: 'Influent Surge Management & pH Neutralization Loops',
            durationMinutes: 1,
            videoUrl: '/videos/etp-ph-control.mp4',
            description: 'Preventing sudden acid spikes from upstream textile/chemical processing vessels.',
          },
        ],
      },
      {
        id: 'mod-etp-102-jar',
        moduleId: 'mod-etp-102-jar',
        order: 2,
        title: 'Six-Paddle Jar Test Calibration & Zeta Potential',
        description: 'Determining exact ppm dosage curves for coagulant and flocculant aids based on turbidity & COD.',
        videos: [
          {
            id: 'vid-etp-102-jar-01',
            videoId: 'vid-etp-102-jar-01',
            order: 1,
            title: 'Six-Paddle Jar Test Protocol (RPM & Settling Velocity)',
            durationMinutes: 1,
            videoUrl: '/videos/etp-jar-test.mp4',
            description: 'Step-by-step flash mix at 120 RPM, slow flocculation at 30 RPM, and 10-minute quiescent settling.',
          },
        ],
      },
    ],
    abilities: [
      {
        id: 'ab-etp102-1',
        courseId: 'course-etp-102',
        order: 1,
        code: '1.1',
        title: 'Coagulation & Jar Test Chemical Dosage',
        description: 'Optimizing chemical precipitation for complex industrial effluents.',
        videoDurationMinutes: 1,
        competencyAreaId: 'ca-etp-chem',
      },
    ],
  },
  {
    id: 'course-etp-201',
    courseId: 'course-etp-201',
    code: 'ETP-201',
    title: 'Activated Sludge Process, F/M Ratio & SVI Control',
    section: 'Effluent Treatment Plants (ETP)',
    category: 'Effluent Treatment Plants (ETP)',
    department: 'ETP Operations',
    jobCategoryId: 'jc-etp-op',
    description:
      'Advanced biological treatment: controlling Sludge Volume Index (SVI), calculating Food-to-Microorganism (F/M) ratios, preventing filamentous bulking, and optimizing RAS/WAS mass balances.',
    thumbnailUrl: '/courses/aeration_blowers.jpg',
    provider: 'Nectar Environmental Academy',
    rating: 4.9,
    reviewCount: 54,
    level: 'Advanced',
    estimatedHours: 5.0,
    passThreshold: 75,
    modules: [
      {
        id: 'mod-etp-201-svi',
        moduleId: 'mod-etp-201-svi',
        order: 1,
        title: 'Sludge Volume Index (SVI) Diagnostics & 30-Min Settlometer Test',
        description: 'Standard 1000 mL graduated cylinder test, calculation of SVI, and troubleshooting ash/foam on surface.',
        videos: [
          {
            id: 'vid-etp-201-svi-01',
            videoId: 'vid-etp-201-svi-01',
            order: 1,
            title: 'Performing the 30-Minute Settlometer Test on Active MLSS',
            durationMinutes: 1,
            videoUrl: '/videos/etp-settlometer.mp4',
            description: 'Differentiating between pinpoint flocs, slow settling, and classic filamentous bulking.',
          },
          {
            id: 'vid-etp-201-svi-02',
            videoId: 'vid-etp-201-svi-02',
            order: 2,
            title: 'SVI Calculation & Filamentous Microscopic Identification',
            durationMinutes: 1,
            videoUrl: '/videos/etp-microscopy.mp4',
            description: 'Identifying Nocardia foaming vs Sphaerotilus natans under 1000x phase-contrast microscopy.',
          },
        ],
      },
      {
        id: 'mod-etp-201-fm',
        moduleId: 'mod-etp-201-fm',
        order: 2,
        title: 'F/M Ratio Balancing & Mean Cell Residence Time (MCRT)',
        description: 'Wasting sludge (WAS) dynamically based on daily BOD load to maintain optimal sludge age of 10-15 days.',
        videos: [
          {
            id: 'vid-etp-201-fm-01',
            videoId: 'vid-etp-201-fm-01',
            order: 1,
            title: 'Daily Sludge Age & WAS Mass Balance Calculation',
            durationMinutes: 1,
            videoUrl: '/videos/etp-was-balance.mp4',
            description: 'Calculating dry solid inventory in aeration tank plus clarifier versus wasted solids.',
          },
        ],
      },
    ],
    abilities: [
      {
        id: 'ab-etp201-1',
        courseId: 'course-etp-201',
        order: 1,
        code: '1.1',
        title: 'Aeration Basin DO & Mixed Liquor Suspended Solids (MLSS)',
        description: 'Maintaining healthy biomass and controlling SVI between 80 and 120 mL/g.',
        videoDurationMinutes: 1,
        competencyAreaId: 'ca-etp-bio',
      },
    ],
  },
  {
    id: 'course-etp-202',
    courseId: 'course-etp-202',
    code: 'ETP-202',
    title: 'Industrial Secondary Clarifiers & Sludge Dewatering Operations',
    section: 'Effluent Treatment Plants (ETP)',
    category: 'Effluent Treatment Plants (ETP)',
    department: 'ETP Operations',
    jobCategoryId: 'jc-etp-op',
    description:
      'Hydraulic loading rate on clarifiers, center well flocculating feed, scum baffle cleaning, filter press cake dryness, and decanter centrifuge torque control.',
    thumbnailUrl: '/courses/sludge_press.jpg',
    provider: 'Nectar Technical Operations',
    rating: 4.7,
    reviewCount: 29,
    level: 'Intermediate',
    estimatedHours: 4.0,
    passThreshold: 70,
    modules: [
      {
        id: 'mod-etp-202-press',
        moduleId: 'mod-etp-202-press',
        order: 1,
        title: 'Recessed Plate Filter Press Cycle Optimization',
        description: 'Sludge conditioning with lime & poly, feed pump hydraulic pressure ramp to 16 bar, and cake moisture verification.',
        videos: [
          {
            id: 'vid-etp-202-press-01',
            videoId: 'vid-etp-202-press-01',
            order: 1,
            title: 'Filter Press Plate Shifting & Cloth High-Pressure Jet Washing',
            durationMinutes: 1,
            videoUrl: '/videos/etp-filter-press.mp4',
            description: 'Preventing cake blowout and maintaining filtrate clarity under high squeeze pressures.',
          },
        ],
      },
    ],
    abilities: [
      {
        id: 'ab-etp202-1',
        courseId: 'course-etp-202',
        order: 1,
        code: '1.1',
        title: 'Clarifier Sludge Dewatering & Solid Waste Logistics',
        description: 'Achieving minimum 30% cake solids for hazardous waste landfill (CHWTSDF) dispatch.',
        videoDurationMinutes: 1,
        competencyAreaId: 'ca-etp-chem',
      },
    ],
  },
  {
    id: 'course-etp-301',
    courseId: 'course-etp-301',
    code: 'ETP-301',
    title: 'Advanced Oxidation Processes (Fenton & Ozone) for Refractory COD',
    section: 'Effluent Treatment Plants (ETP)',
    category: 'Effluent Treatment Plants (ETP)',
    department: 'ETP Engineering',
    jobCategoryId: 'jc-etp-op',
    description:
      'Hydroxyl radical generation chemistry: classic Fenton reaction (H2O2 + Fe2+), pH 3.0 control, UV-assisted Fenton, ozone gas diffusion contactors, and quenching residual hydrogen peroxide.',
    thumbnailUrl: '/courses/aop_ozone_treatment.jpg',
    provider: 'Nectar Environmental Academy',
    rating: 4.9,
    reviewCount: 36,
    level: 'Advanced',
    estimatedHours: 5.0,
    passThreshold: 75,
    modules: [
      {
        id: 'mod-etp-301-fenton',
        moduleId: 'mod-etp-301-fenton',
        order: 1,
        title: 'Fenton Reactor Chemical Dosing & Stoichiometry',
        description: 'Calculating H2O2:COD ratio, ferrous sulfate catalyst addition, and rapid exothermic heat dissipation.',
        videos: [
          {
            id: 'vid-etp-301-fen-01',
            videoId: 'vid-etp-301-fen-01',
            order: 1,
            title: 'Fenton Reagent Preparation & ORP Monitoring',
            durationMinutes: 1,
            videoUrl: '/videos/etp-fenton-reagents.mp4',
            description: 'Precise dosing of 50% technical hydrogen peroxide with specialized safety gear and metering pumps.',
          },
        ],
      },
    ],
    abilities: [
      {
        id: 'ab-etp301-1',
        courseId: 'course-etp-301',
        order: 1,
        code: '1.1',
        title: 'AOP Reaction Kinetics & Refractory COD Degradation',
        description: 'Breaking recalcitrant aromatic rings in pesticide and dye industrial wastewaters.',
        videoDurationMinutes: 1,
        competencyAreaId: 'ca-etp-chem',
      },
    ],
  },

  // =========================================================================
  // 2. WATER TREATMENT PLANTS & REVERSE OSMOSIS (WTP & RO) - 5 COURSES
  // =========================================================================
  {
    id: 'course-ops-301',
    courseId: 'course-ops-301',
    code: 'RO-301',
    title: 'Industrial RO Membrane Operations & CIP Descaling',
    section: 'Water Treatment Plants (WTP)',
    category: 'Water Treatment Plants (WTP)',
    department: 'WTP / RO Operations',
    jobCategoryId: 'jc-wtp-tech',
    description:
      'Standard operating procedures for spiral-wound thin film composite RO membranes: SDI index monitoring, antiscalant dosing stoichiometry, salt rejection normalization, and two-stage chemical CIP.',
    thumbnailUrl: '/courses/ro_membrane.jpg',
    provider: 'Nectar Membrane Engineering Unit',
    rating: 4.9,
    reviewCount: 48,
    level: 'Intermediate',
    estimatedHours: 5.0,
    passThreshold: 75,
    modules: [
      {
        id: 'mod-ro-301-sdi',
        moduleId: 'mod-ro-301-sdi',
        order: 1,
        title: 'Silt Density Index (SDI) Testing & Cartridge Micron Filters',
        description: 'SDI15 field measurement at 30 psi, 5-micron spun filter replacement, and delta-P differential tracking.',
        videos: [
          {
            id: 'vid-ro-301-sdi-01',
            videoId: 'vid-ro-301-sdi-01',
            order: 1,
            title: 'Silt Density Index (SDI15) Test Execution on RO Feed',
            durationMinutes: 1,
            videoUrl: '/videos/ro-sdi-test.mp4',
            description: 'Calibrating manual test cell, timing 500 mL filtrate intervals, and calculating SDI15 below 3.0.',
          },
          {
            id: 'vid-ro-301-sdi-02',
            videoId: 'vid-ro-301-sdi-02',
            order: 2,
            title: 'Cartridge Filter Housing Bleeding & Seal Integrity',
            durationMinutes: 1,
            videoUrl: '/videos/ro-cartridge-swap.mp4',
            description: 'Sanitary cartridge replacement without bypass leakage into high-pressure pumps.',
          },
        ],
      },
      {
        id: 'mod-ro-301-cip',
        moduleId: 'mod-ro-301-cip',
        order: 2,
        title: 'Two-Stage Clean-In-Place (CIP) Protocol (Low pH & High pH)',
        description: 'Citric acid descaling for calcium carbonate, followed by caustic/surfactant cleaning for biofouling.',
        videos: [
          {
            id: 'vid-ro-301-cip-01',
            videoId: 'vid-ro-301-cip-01',
            order: 1,
            title: 'CIP Chemical Skid Preparation, Heating & Recirculation',
            durationMinutes: 1,
            videoUrl: '/videos/ro-cip-skid.mp4',
            description: 'Maintaining 35-38°C CIP tank temperature and laminar circulation velocity across pressure vessels.',
          },
        ],
      },
    ],
    abilities: [
      {
        id: 'ab-ro-1',
        courseId: 'course-ops-301',
        order: 1,
        code: '1.1',
        title: 'Silt Density Index (SDI) & Pre-treatment Cartridge Filter Delta-P',
        description: 'SDI15 measurement protocol using 0.45 micron filter pads at 30 psi feed pressure.',
        videoDurationMinutes: 1,
        competencyAreaId: 'ca-wtp-ro',
      },
      {
        id: 'ab-ro-2',
        courseId: 'course-ops-301',
        order: 2,
        code: '1.2',
        title: 'High-Pressure Pump Start-up Sequencing & Water Hammer Prevention',
        description: 'Automatic soft-start ramp rate, concentrate control valve positioning, and slow pressurized filling.',
        videoDurationMinutes: 1,
        competencyAreaId: 'ca-wtp-ro',
      },
    ],
  },
  {
    id: 'course-ro-302',
    courseId: 'course-ro-302',
    code: 'RO-302',
    title: 'RO Scaling, Biofouling Diagnosis & Normalized Permeate Decline',
    section: 'Water Treatment Plants (WTP)',
    category: 'Water Treatment Plants (WTP)',
    department: 'WTP / RO Operations',
    jobCategoryId: 'jc-wtp-tech',
    description:
      'ASTM D4516 normalization equations: temperature correction factor (TCF), salt passage trending, delta-P profiling across stages, and autopsy analysis of foulants on membrane leaves.',
    thumbnailUrl: '/courses/ro_membrane_fouling.jpg',
    provider: 'Nectar Membrane Engineering Unit',
    rating: 4.8,
    reviewCount: 33,
    level: 'Advanced',
    estimatedHours: 4.5,
    passThreshold: 75,
    modules: [
      {
        id: 'mod-ro-302-norm',
        moduleId: 'mod-ro-302-norm',
        order: 1,
        title: 'ASTM D4516 Normalization & Trend Analysis',
        description: 'Separating seasonal feed temperature variations from true mineral scaling and membrane compaction.',
        videos: [
          {
            id: 'vid-ro-302-norm-01',
            videoId: 'vid-ro-302-norm-01',
            order: 1,
            title: 'Calculating Normalized Flow Rate & Salt Passage',
            durationMinutes: 1,
            videoUrl: '/videos/ro-normalization.mp4',
            description: 'Spotting early 10% permeate decline before irreversible silica scaling takes place.',
          },
        ],
      },
    ],
    abilities: [
      {
        id: 'ab-ro302-1',
        courseId: 'course-ro-302',
        order: 1,
        code: '1.1',
        title: 'Membrane Fouling Profiling & Normalized Diagnostics',
        description: 'Diagnosing Stage 1 biological slime vs Stage 2 gypsum / silica scale.',
        videoDurationMinutes: 1,
        competencyAreaId: 'ca-wtp-ro',
      },
    ],
  },
  {
    id: 'course-wtp-101',
    courseId: 'course-wtp-101',
    code: 'WTP-101',
    title: 'Raw Water Pretreatment: Dual Media & Activated Carbon Filters',
    section: 'Water Treatment Plants (WTP)',
    category: 'Water Treatment Plants (WTP)',
    department: 'WTP / RO Operations',
    jobCategoryId: 'jc-wtp-tech',
    description:
      'Media filter hydraulics: gravel underdrains, anthracite and quartz sand stratification, air scouring backwash cycles, iodine value of granular activated carbon (GAC), and dechlorination.',
    thumbnailUrl: '/courses/water_lab_testing.jpg',
    provider: 'Nectar Technical Operations',
    rating: 4.7,
    reviewCount: 27,
    level: 'Foundation',
    estimatedHours: 3.5,
    passThreshold: 70,
    modules: [
      {
        id: 'mod-wtp-101-dmf',
        moduleId: 'mod-wtp-101-dmf',
        order: 1,
        title: 'Dual Media Filter (DMF) Backwash & Air Scour Sequencing',
        description: 'Multi-port valve actuation, differential pressure limits, and bed expansion verification.',
        videos: [
          {
            id: 'vid-wtp-101-dmf-01',
            videoId: 'vid-wtp-101-dmf-01',
            order: 1,
            title: 'DMF Automatic Backwash Cycle & Turbidity Breakthrough',
            durationMinutes: 1,
            videoUrl: '/videos/wtp-dmf-backwash.mp4',
            description: 'Air scouring at 50 m3/h followed by water backwash to prevent mud-ball formation.',
          },
        ],
      },
    ],
    abilities: [
      {
        id: 'ab-wtp101-1',
        courseId: 'course-wtp-101',
        order: 1,
        code: '1.1',
        title: 'Media Filter Operation & Differential Pressure Backwash',
        description: 'Maintaining clear raw water turbidity below 1.0 NTU for downstream RO feed.',
        videoDurationMinutes: 1,
        competencyAreaId: 'ca-wtp-pre',
      },
    ],
  },
  {
    id: 'course-wtp-201',
    courseId: 'course-wtp-201',
    code: 'WTP-201',
    title: 'Industrial Demineralization (DM) & Mixed Bed Ion Exchange',
    section: 'Water Treatment Plants (WTP)',
    category: 'Water Treatment Plants (WTP)',
    department: 'WTP / RO Operations',
    jobCategoryId: 'jc-wtp-tech',
    description:
      'Strong acid cation (SAC) and strong base anion (SBA) resin chemistry, regeneration with hydrochloric acid (HCl) and sodium hydroxide (NaOH), and ultra-pure mixed bed polishing (<0.1 uS/cm).',
    thumbnailUrl: '/courses/edi_purification.jpg',
    provider: 'Nectar Technical Operations',
    rating: 4.8,
    reviewCount: 35,
    level: 'Intermediate',
    estimatedHours: 4.0,
    passThreshold: 75,
    modules: [
      {
        id: 'mod-wtp-201-dm',
        moduleId: 'mod-wtp-201-dm',
        order: 1,
        title: 'Cation & Anion Resin Regeneration Chemistry',
        description: 'Step-acid injection, slow displacement rinse, and silica slip monitoring on anion exhaustion.',
        videos: [
          {
            id: 'vid-wtp-201-dm-01',
            videoId: 'vid-wtp-201-dm-01',
            order: 1,
            title: 'Executing DM Plant Acid & Caustic Chemical Regeneration',
            durationMinutes: 1,
            videoUrl: '/videos/wtp-dm-regen.mp4',
            description: 'Hydrochloric acid diluter ejectors and caustic heater temperature control at 45°C.',
          },
        ],
      },
    ],
    abilities: [
      {
        id: 'ab-wtp201-1',
        courseId: 'course-wtp-201',
        order: 1,
        code: '1.1',
        title: 'Ion Exchange Regeneration & Conductivity Monitoring',
        description: 'Producing boiler feed demineralized water with zero silica and sodium slip.',
        videoDurationMinutes: 1,
        competencyAreaId: 'ca-wtp-dm',
      },
    ],
  },
  {
    id: 'course-wtp-301',
    courseId: 'course-wtp-301',
    code: 'UF-301',
    title: 'Ultrafiltration (UF) Flux Maintenance & CEB Protocols',
    section: 'Water Treatment Plants (WTP)',
    category: 'Water Treatment Plants (WTP)',
    department: 'WTP / RO Operations',
    jobCategoryId: 'jc-wtp-tech',
    description:
      'Hollow fiber PVDF ultrafiltration membranes: TMP (Transmembrane Pressure) trending, backpulse with chlorine, Chemically Enhanced Backwash (CEB), and automated bubble point integrity testing.',
    thumbnailUrl: '/courses/uf_membrane_system.jpg',
    provider: 'Nectar Membrane Engineering Unit',
    rating: 4.9,
    reviewCount: 39,
    level: 'Advanced',
    estimatedHours: 4.0,
    passThreshold: 75,
    modules: [
      {
        id: 'mod-wtp-301-uf',
        moduleId: 'mod-wtp-301-uf',
        order: 1,
        title: 'UF Module Integrity & Pressure Decay Test (PDT)',
        description: 'Detecting breached hollow fiber capillaries through automated pneumatic pressure hold tests.',
        videos: [
          {
            id: 'vid-wtp-301-uf-01',
            videoId: 'vid-wtp-301-uf-01',
            order: 1,
            title: 'Conducting Pressure Decay Test & Fiber Pinning',
            durationMinutes: 1,
            videoUrl: '/videos/wtp-uf-pinning.mp4',
            description: 'Locating damaged fiber lumens using bubble sight glass and sealing with titanium pins.',
          },
        ],
      },
    ],
    abilities: [
      {
        id: 'ab-wtp301-1',
        courseId: 'course-wtp-301',
        order: 1,
        code: '1.1',
        title: 'UF Transmembrane Pressure & CEB Dosing',
        description: 'Controlling irreversible particulate fouling to sustain design permeate flux.',
        videoDurationMinutes: 1,
        competencyAreaId: 'ca-wtp-ro',
      },
    ],
  },

  // =========================================================================
  // 3. SEWAGE TREATMENT PLANTS (STP) - 4 COURSES
  // =========================================================================
  {
    id: 'course-stp-101',
    courseId: 'course-stp-101',
    code: 'STP-101',
    title: 'Sewage Treatment Plant Principles & MBBR Biofilm Management',
    section: 'Sewage Treatment Plants (STP)',
    category: 'Sewage Treatment Plants (STP)',
    department: 'STP Operations',
    jobCategoryId: 'jc-stp-op',
    description:
      'Moving Bed Biofilm Reactor (MBBR) fluidization: carrier filling fraction (30-60%), biofilm thickness control, coarse bubble grid aeration, screen sieves, and total ammoniacal nitrogen oxidation.',
    thumbnailUrl: '/courses/mbbr_media.jpg',
    provider: 'Nectar Municipal & Industrial STP Unit',
    rating: 4.8,
    reviewCount: 38,
    level: 'Foundation',
    estimatedHours: 4.0,
    passThreshold: 70,
    modules: [
      {
        id: 'mod-stp-101-mbbr',
        moduleId: 'mod-stp-101-mbbr',
        order: 1,
        title: 'MBBR Carrier Hydrodynamics & Media Retention Sieve Cleansing',
        description: 'Preventing media clogging against outlet retention screens and maintaining carrier suspension.',
        videos: [
          {
            id: 'vid-stp-101-mbbr-01',
            videoId: 'vid-stp-101-mbbr-01',
            order: 1,
            title: 'Carrier Biofilm Growth Inspection & Media Retention Weirs',
            durationMinutes: 1,
            videoUrl: '/videos/stp-mbbr-inspection.mp4',
            description: 'Inspecting Virgin vs Mature biofilm carriers and measuring volatile attachment solids.',
          },
        ],
      },
    ],
    abilities: [
      {
        id: 'ab-stp101-1',
        courseId: 'course-stp-101',
        order: 1,
        code: '1.1',
        title: 'MBBR Fluidization & Biofilm Nitrification',
        description: 'Achieving complete conversion of NH4-N to NO3-N in municipal and commercial STP facilities.',
        videoDurationMinutes: 1,
        competencyAreaId: 'ca-stp-bio',
      },
    ],
  },
  {
    id: 'course-stp-102',
    courseId: 'course-stp-102',
    code: 'STP-102',
    title: 'Sequential Batch Reactor (SBR) Cyclic Decanting & Denitrification',
    section: 'Sewage Treatment Plants (STP)',
    category: 'Sewage Treatment Plants (STP)',
    department: 'STP Operations',
    jobCategoryId: 'jc-stp-op',
    description:
      'SBR phase programming: Fill-Aeration-Anoxic-Settle-Decant cycles, automated scupper decanter winch mechanisms, DO trajectory tracking, and simultaneous nitrification-denitrification (SND).',
    thumbnailUrl: '/courses/sbr_reactor.jpg',
    provider: 'Nectar Municipal & Industrial STP Unit',
    rating: 4.9,
    reviewCount: 41,
    level: 'Intermediate',
    estimatedHours: 4.5,
    passThreshold: 75,
    modules: [
      {
        id: 'mod-stp-102-cycle',
        moduleId: 'mod-stp-102-cycle',
        order: 1,
        title: 'PLC Time-Slice Calibration for SBR Phase Cycles',
        description: 'Tuning anoxic denitrification phase time versus aerobic blowers to strip nitrates efficiently.',
        videos: [
          {
            id: 'vid-stp-102-cyc-01',
            videoId: 'vid-stp-102-cyc-01',
            order: 1,
            title: 'Decanter Arm Scum Guard Calibration & Decant Depth',
            durationMinutes: 1,
            videoUrl: '/videos/stp-decanter.mp4',
            description: 'Preventing surface foam suction into treated water sump during rapid motorized decant.',
          },
        ],
      },
    ],
    abilities: [
      {
        id: 'ab-stp102-1',
        courseId: 'course-stp-102',
        order: 1,
        code: '1.1',
        title: 'SBR Batch Cycle Programming & Nitrogen Removal',
        description: 'Achieving total nitrogen discharge levels below 10 ppm for environmental discharge compliance.',
        videoDurationMinutes: 1,
        competencyAreaId: 'ca-stp-bio',
      },
    ],
  },
  {
    id: 'course-stp-201',
    courseId: 'course-stp-201',
    code: 'STP-201',
    title: 'Submerged Membrane Bioreactor (MBR) Permeate Extraction & Air Scour',
    section: 'Sewage Treatment Plants (STP)',
    category: 'Sewage Treatment Plants (STP)',
    department: 'STP Operations',
    jobCategoryId: 'jc-stp-op',
    description:
      'MBR flat sheet and hollow fiber cassettes: operating with high MLSS (8,000-12,000 mg/L), continuous coarse air scour for cake layer prevention, relax cycles, and sodium hypochlorite recovery cleaning.',
    thumbnailUrl: '/courses/stp_plant_real.jpg',
    provider: 'Nectar Municipal & Industrial STP Unit',
    rating: 4.9,
    reviewCount: 35,
    level: 'Advanced',
    estimatedHours: 5.0,
    passThreshold: 75,
    modules: [
      {
        id: 'mod-stp-201-mbr',
        moduleId: 'mod-stp-201-mbr',
        order: 1,
        title: 'MBR Aeration Blower Cycling & Permeate Pump Control',
        description: 'Intermittent 9-min suction / 1-min relaxation routines and TMP alarm limits.',
        videos: [
          {
            id: 'vid-stp-201-mbr-01',
            videoId: 'vid-stp-201-mbr-01',
            order: 1,
            title: 'Submerged MBR Cassette Hoisting & In-Situ Hypochlorite CIP',
            durationMinutes: 1,
            videoUrl: '/videos/stp-mbr-cip.mp4',
            description: 'Back-pulsing 500 ppm NaOCl solution through permeate manifold to remove extracellular polymeric substances.',
          },
        ],
      },
    ],
    abilities: [
      {
        id: 'ab-stp201-1',
        courseId: 'course-stp-201',
        order: 1,
        code: '1.1',
        title: 'MBR Membrane Flux Maintenance & Extracellular Polymers',
        description: 'Operating compact MBR plants producing crystal clear reclaimed water for industrial reuse.',
        videoDurationMinutes: 1,
        competencyAreaId: 'ca-stp-bio',
      },
    ],
  },
  {
    id: 'course-stp-202',
    courseId: 'course-stp-202',
    code: 'STP-202',
    title: 'Disinfection Protocols: Chlorination, UV Curing & Tertiary Polishing',
    section: 'Sewage Treatment Plants (STP)',
    category: 'Sewage Treatment Plants (STP)',
    department: 'STP Operations',
    jobCategoryId: 'jc-stp-op',
    description:
      'Pathogen removal engineering: sodium hypochlorite dosing contact tanks (CT values), medium-pressure ultraviolet (UV) lamp sleeve cleaning, quartz wiping mechanisms, and ozone polishing.',
    thumbnailUrl: '/courses/skid_stp.jpg',
    provider: 'Nectar Municipal & Industrial STP Unit',
    rating: 4.7,
    reviewCount: 26,
    level: 'Foundation',
    estimatedHours: 3.5,
    passThreshold: 70,
    modules: [
      {
        id: 'mod-stp-202-disinf',
        moduleId: 'mod-stp-202-disinf',
        order: 1,
        title: 'UV Reactor Quartz Sleeve Cleaning & Transmittance Monitoring',
        description: 'Manual and automatic wiper maintenance to prevent calcium scaling on 254 nm germicidal lamps.',
        videos: [
          {
            id: 'vid-stp-202-uv-01',
            videoId: 'vid-stp-202-uv-01',
            order: 1,
            title: 'UV Lamp Replacement, Ballast Checks & UVT Validation',
            durationMinutes: 1,
            videoUrl: '/videos/stp-uv-system.mp4',
            description: 'Ensuring zero fecal coliform count in treated sewage for gardening and toilet flushing reuse.',
          },
        ],
      },
    ],
    abilities: [
      {
        id: 'ab-stp202-1',
        courseId: 'course-stp-202',
        order: 1,
        code: '1.1',
        title: 'Disinfection Chemistry & Coliform Compliance',
        description: 'Maintaining residual chlorine and germicidal UV dosage within regulatory limits.',
        videoDurationMinutes: 1,
        competencyAreaId: 'ca-stp-dis',
      },
    ],
  },

  // =========================================================================
  // 4. ZERO LIQUID DISCHARGE (ZLD) - 4 COURSES
  // =========================================================================
  {
    id: 'course-zld-401',
    courseId: 'course-zld-401',
    code: 'MEE-401',
    title: 'Thermal Evaporation Systems: MEE & ATFD Operation',
    section: 'Zero Liquid Discharge (ZLD)',
    category: 'Zero Liquid Discharge (ZLD)',
    department: 'ZLD Operations',
    jobCategoryId: 'jc-zld-eng',
    description:
      'Operation of falling-film and forced-circulation Multiple Effect Evaporators (MEE), barometric condenser vacuum systems, steam economy balancing, and Agitated Thin Film Dryer (ATFD) salt crystallization.',
    thumbnailUrl: '/courses/multiple_effect_evaporator.jpg',
    provider: 'Nectar Thermal & ZLD Division',
    rating: 4.9,
    reviewCount: 52,
    level: 'Advanced',
    estimatedHours: 5.5,
    passThreshold: 75,
    modules: [
      {
        id: 'mod-zld-401-mee',
        moduleId: 'mod-zld-401-mee',
        order: 1,
        title: 'Multiple Effect Evaporator Vacuum Gradient & Steam Economy',
        description: 'Balancing inter-effect pressure drops from Effect 1 (+0.5 bar) down to Effect 3 (-0.8 bar vacuum).',
        videos: [
          {
            id: 'vid-zld-401-mee-01',
            videoId: 'vid-zld-401-mee-01',
            order: 1,
            title: 'Steam Jet Ejector & Barometric Seal Leg Hydrodynamics',
            durationMinutes: 1,
            videoUrl: '/videos/mee-steam-ejector.mp4',
            description: 'Maintaining 10-meter hydrostatic barometric water leg to pull deep vacuum on vapor bodies.',
          },
          {
            id: 'vid-zld-401-mee-02',
            videoId: 'vid-zld-401-mee-02',
            order: 2,
            title: 'Forced Circulation Pump Amperage & Calandria Scaling',
            durationMinutes: 1,
            videoUrl: '/videos/mee-forced-circulation.mp4',
            description: 'Preventing tube pluggage when handling high total dissolved solids (TDS > 150,000 ppm).',
          },
        ],
      },
      {
        id: 'mod-zld-401-atfd',
        moduleId: 'mod-zld-401-atfd',
        order: 2,
        title: 'Agitated Thin Film Dryer (ATFD) Blade Clearance & Salt Discharge',
        description: 'Rotor blade scraping mechanisms, steam jacket thermal conduction, and dry powder salt bag packing.',
        videos: [
          {
            id: 'vid-zld-401-atfd-01',
            videoId: 'vid-zld-401-atfd-01',
            order: 1,
            title: 'ATFD Rotor Blade Gap Calibration & Rotary Joint Maintenance',
            durationMinutes: 1,
            videoUrl: '/videos/mee-atfd-maintenance.mp4',
            description: 'Checking 1.5 mm blade-to-shell tolerance to prevent metal grinding and motor overload.',
          },
        ],
      },
    ],
    abilities: [
      {
        id: 'ab-mee-1',
        courseId: 'course-zld-401',
        order: 1,
        code: '1.1',
        title: 'Thermo-Compressor Steam Jet Ejector & Vacuum Gradient Balancing',
        description: 'Calibrating multi-stage steam ejectors and barometric seal legs to maintain inter-effect vacuum gradient.',
        videoDurationMinutes: 1,
        competencyAreaId: 'ca-zld-mee',
      },
    ],
  },
  {
    id: 'course-zld-302',
    courseId: 'course-zld-302',
    code: 'ZLD-302',
    title: 'High Recovery RO & Brine Concentrator Integration',
    section: 'Zero Liquid Discharge (ZLD)',
    category: 'Zero Liquid Discharge (ZLD)',
    department: 'ZLD Operations',
    jobCategoryId: 'jc-zld-eng',
    description:
      'High-pressure reverse osmosis (HPRO / DTRO) operating up to 120 bar: concentration of RO reject up to 80,000 ppm TDS prior to thermal evaporation, reducing MEE capital and steam footprint.',
    thumbnailUrl: '/courses/brine_desalination.jpg',
    provider: 'Nectar Thermal & ZLD Division',
    rating: 4.8,
    reviewCount: 37,
    level: 'Advanced',
    estimatedHours: 4.5,
    passThreshold: 75,
    modules: [
      {
        id: 'mod-zld-302-hpro',
        moduleId: 'mod-zld-302-hpro',
        order: 1,
        title: 'Disc Tube RO (DTRO) Construction & Hydraulics',
        description: 'Open-channel disc cushion membranes, hydraulic plunger pumps, and osmotic pressure management.',
        videos: [
          {
            id: 'vid-zld-302-dtro-01',
            videoId: 'vid-zld-302-dtro-01',
            order: 1,
            title: 'Operating 120 Bar DTRO Plunger Pumps & Cushion Modules',
            durationMinutes: 1,
            videoUrl: '/videos/zld-dtro-operation.mp4',
            description: 'Mitigating colloidal polarization in high-strength reject water streams.',
          },
        ],
      },
    ],
    abilities: [
      {
        id: 'ab-zld302-1',
        courseId: 'course-zld-302',
        order: 1,
        code: '1.1',
        title: 'High Recovery Brine Concentration Hydraulics',
        description: 'Reaching 85-90% overall water recovery before feed enters thermal evaporation.',
        videoDurationMinutes: 1,
        competencyAreaId: 'ca-zld-mee',
      },
    ],
  },
  {
    id: 'course-zld-303',
    courseId: 'course-zld-303',
    code: 'MEE-402',
    title: 'Multi-Effect Evaporator Vacuum Gradient & Entrainment Prevention',
    section: 'Zero Liquid Discharge (ZLD)',
    category: 'Zero Liquid Discharge (ZLD)',
    department: 'ZLD Operations',
    jobCategoryId: 'jc-zld-eng',
    description:
      'Vapor-liquid separation geometry: chevron mist eliminators, wire mesh demisters, entrainment carryover prevention in condensate polishing sumps, and CIP caustic boiling routines.',
    thumbnailUrl: '/courses/industrial_evaporator.jpg',
    provider: 'Nectar Thermal & ZLD Division',
    rating: 4.7,
    reviewCount: 28,
    level: 'Intermediate',
    estimatedHours: 4.0,
    passThreshold: 70,
    modules: [
      {
        id: 'mod-zld-303-demist',
        moduleId: 'mod-zld-303-demist',
        order: 1,
        title: 'Demister Pad Washing & Vapor Quality Control',
        description: 'Preventing TDS carryover into steam condensate to protect boiler feed return loops.',
        videos: [
          {
            id: 'vid-zld-303-dem-01',
            videoId: 'vid-zld-303-dem-01',
            order: 1,
            title: 'Vapor Duct Demister Pad Inspection & CIP Boilout',
            durationMinutes: 1,
            videoUrl: '/videos/mee-demister-cleaning.mp4',
            description: 'Executing hot 2% caustic soda wash through calandria tubes to dissolve organic scaling.',
          },
        ],
      },
    ],
    abilities: [
      {
        id: 'ab-zld303-1',
        courseId: 'course-zld-303',
        order: 1,
        code: '1.1',
        title: 'Vapor Separation & Condensate Quality Safeguards',
        description: 'Ensuring evaporator condensate conductivity remains below 50 uS/cm for recycling.',
        videoDurationMinutes: 1,
        competencyAreaId: 'ca-zld-mee',
      },
    ],
  },
  {
    id: 'course-zld-402',
    courseId: 'course-zld-402',
    code: 'ZLD-402',
    title: 'Centrifuge & Pusher Filtration for Industrial Salt Crystallization',
    section: 'Zero Liquid Discharge (ZLD)',
    category: 'Zero Liquid Discharge (ZLD)',
    department: 'ZLD Operations',
    jobCategoryId: 'jc-zld-eng',
    description:
      'Fractional crystallization of sodium sulfate (Na2SO4) and sodium chloride (NaCl): cooling crystallizers, basket centrifuges, pusher centrifuges, cake washing cycles, and moisture reduction.',
    thumbnailUrl: '/courses/salt_crystallization.jpg',
    provider: 'Nectar Thermal & ZLD Division',
    rating: 4.8,
    reviewCount: 30,
    level: 'Advanced',
    estimatedHours: 4.5,
    passThreshold: 75,
    modules: [
      {
        id: 'mod-zld-402-cent',
        moduleId: 'mod-zld-402-cent',
        order: 1,
        title: 'Two-Stage Pusher Centrifuge Stroke Frequency & Cake Purity',
        description: 'Adjusting hydraulic stroke speed and mother liquor wash liquor ratio to produce dry saleable salts.',
        videos: [
          {
            id: 'vid-zld-402-cent-01',
            videoId: 'vid-zld-402-cent-01',
            order: 1,
            title: 'Pusher Centrifuge Screen Wedge Wire Clearance & Cake Dewatering',
            durationMinutes: 1,
            videoUrl: '/videos/zld-pusher-centrifuge.mp4',
            description: 'Vibration monitoring and hydraulic oil pressure tuning for heavy slurry crystallization.',
          },
        ],
      },
    ],
    abilities: [
      {
        id: 'ab-zld402-1',
        courseId: 'course-zld-402',
        order: 1,
        code: '1.1',
        title: 'Industrial Salt Separation & Cake Moisture Management',
        description: 'Achieving pure, dry crystalline solids for industrial by-product recycling.',
        videoDurationMinutes: 1,
        competencyAreaId: 'ca-zld-mee',
      },
    ],
  },

  // =========================================================================
  // 5. ENVIRONMENTAL CONSULTING SERVICES - 4 COURSES
  // =========================================================================
  {
    id: 'course-env-101',
    courseId: 'course-env-101',
    code: 'ENV-101',
    title: 'CPCB & SPCB Environmental Statutory Compliance & Form V Filing',
    section: 'Environmental Consulting Services',
    category: 'Environmental Consulting Services',
    department: 'Environmental Audits & Consulting',
    jobCategoryId: 'jc-env-csl',
    description:
      'Indian regulatory statutory framework: Water (Prevention & Control of Pollution) Act 1974, Air Act 1981, Consent to Establish (CTE), Consent to Operate (CTO) renewal, and Environmental Statement Form V preparation.',
    thumbnailUrl: '/courses/environmental_audit.jpg',
    provider: 'Nectar Regulatory Compliance Cell',
    rating: 4.9,
    reviewCount: 46,
    level: 'Intermediate',
    estimatedHours: 4.0,
    passThreshold: 70,
    modules: [
      {
        id: 'mod-env-101-forms',
        moduleId: 'mod-env-101-forms',
        order: 1,
        title: 'Form V Environmental Statement Audit & Mass Balance Tables',
        description: 'Water consumption per unit of product output, raw material audit, and pollution load calculations.',
        videos: [
          {
            id: 'vid-env-101-form-01',
            videoId: 'vid-env-101-form-01',
            order: 1,
            title: 'Drafting Form V Part A-I Schedules for SPCB Submission',
            durationMinutes: 1,
            videoUrl: '/videos/env-form-v.mp4',
            description: 'Compiling real site data: water balances, hazardous waste inventories, and stack emission logs.',
          },
        ],
      },
    ],
    abilities: [
      {
        id: 'ab-env101-1',
        courseId: 'course-env-101',
        order: 1,
        code: '1.1',
        title: 'Statutory Pollution Board Filings & Audit Readiness',
        description: 'Preparing error-free CTO renewal dossiers and annual environmental statements.',
        videoDurationMinutes: 1,
        competencyAreaId: 'ca-env-reg',
      },
    ],
  },
  {
    id: 'course-env-201',
    courseId: 'course-env-201',
    code: 'ENV-201',
    title: 'Environmental Impact Assessment (EIA) & Baseline Monitoring',
    section: 'Environmental Consulting Services',
    category: 'Environmental Consulting Services',
    department: 'Environmental Audits & Consulting',
    jobCategoryId: 'jc-env-csl',
    description:
      'MoEFCC EIA Notification 2006 protocols: Terms of Reference (ToR), 10 km buffer baseline ambient air quality monitoring (AAQM), groundwater sampling grids, noise contour mapping, and public hearing documentation.',
    thumbnailUrl: '/courses/eia_water_sampling.jpg',
    provider: 'Nectar Regulatory Compliance Cell',
    rating: 4.8,
    reviewCount: 32,
    level: 'Advanced',
    estimatedHours: 5.0,
    passThreshold: 75,
    modules: [
      {
        id: 'mod-env-201-eia',
        moduleId: 'mod-env-201-eia',
        order: 1,
        title: 'Baseline Air, Water & Noise Survey Methodology',
        description: 'Calibrating respirable dust samplers (PM10/PM2.5), grab sampling of industrial groundwater aquifers, and Leq noise logs.',
        videos: [
          {
            id: 'vid-env-201-eia-01',
            videoId: 'vid-env-201-eia-01',
            order: 1,
            title: 'Ambient Air Quality High Volume Sampler Deployment',
            durationMinutes: 1,
            videoUrl: '/videos/env-air-monitoring.mp4',
            description: 'Filter paper conditioning, desiccator weighing, and flow rate calibration across 8 monitoring stations.',
          },
        ],
      },
    ],
    abilities: [
      {
        id: 'ab-env201-1',
        courseId: 'course-env-201',
        order: 1,
        code: '1.1',
        title: 'EIA Baseline Data Acquisition & Dispersion Modeling',
        description: 'Executing rigorous baseline monitoring aligned with MoEFCC and CPCB guidelines.',
        videoDurationMinutes: 1,
        competencyAreaId: 'ca-env-eia',
      },
    ],
  },
  {
    id: 'course-env-202',
    courseId: 'course-env-202',
    code: 'ENV-202',
    title: 'Online Continuous Effluent Monitoring Systems (OCEMS) Calibration',
    section: 'Environmental Consulting Services',
    category: 'Environmental Consulting Services',
    department: 'Environmental Audits & Consulting',
    jobCategoryId: 'jc-env-csl',
    description:
      'Real-time CPCB/SPCB portal telemetry integration: optical UV-Vis spectrophotometers for COD/BOD, electromagnetic flowmeters, optical pH probes, turbidity sensors, and data logger cloud sync.',
    thumbnailUrl: '/courses/ocems_telemetry.jpg',
    provider: 'Nectar Regulatory Compliance Cell',
    rating: 4.9,
    reviewCount: 40,
    level: 'Intermediate',
    estimatedHours: 4.0,
    passThreshold: 75,
    modules: [
      {
        id: 'mod-env-202-ocems',
        moduleId: 'mod-env-202-ocems',
        order: 1,
        title: 'OCEMS Probe Calibration & Zero/Span Gas/Buffer Checks',
        description: 'Bi-weekly calibration protocols to prevent false exceedance alerts on the state pollution portal.',
        videos: [
          {
            id: 'vid-env-202-oc-01',
            videoId: 'vid-env-202-oc-01',
            order: 1,
            title: 'Optical COD/BOD Probe Lens Wiping & Buffer Verification',
            durationMinutes: 1,
            videoUrl: '/videos/env-ocems-probe.mp4',
            description: 'Compensating for biofilm interference and verifying data transmission packets to CPCB server.',
          },
        ],
      },
    ],
    abilities: [
      {
        id: 'ab-env202-1',
        courseId: 'course-env-202',
        order: 1,
        code: '1.1',
        title: 'OCEMS Sensor Maintenance & Cloud Telemetry Validation',
        description: 'Maintaining 95%+ uptime on pollution control board real-time transmission streams.',
        videoDurationMinutes: 1,
        competencyAreaId: 'ca-env-reg',
      },
    ],
  },
  {
    id: 'course-env-301',
    courseId: 'course-env-301',
    code: 'ENV-301',
    title: 'Hazardous Waste Categorization, Manifests & Form 10 Logistics',
    section: 'Environmental Consulting Services',
    category: 'Environmental Consulting Services',
    department: 'Environmental Audits & Consulting',
    jobCategoryId: 'jc-env-csl',
    description:
      'Hazardous & Other Wastes Rules 2016: Schedule I/II/III classification, storage shed containment requirements, color-coded barcoded labeling, Form 10 six-copy manifest handling, and authorized TSDF dispatch.',
    thumbnailUrl: '/courses/chemical_safety.jpg',
    provider: 'Nectar Regulatory Compliance Cell',
    rating: 4.8,
    reviewCount: 29,
    level: 'Intermediate',
    estimatedHours: 3.5,
    passThreshold: 70,
    modules: [
      {
        id: 'mod-env-301-haz',
        moduleId: 'mod-env-301-haz',
        order: 1,
        title: 'Hazardous Waste Manifest (Form 10) Six-Copy Workflow',
        description: 'Tracking waste transit from industrial generator to certified common treatment facility (CHWTSDF).',
        videos: [
          {
            id: 'vid-env-301-haz-01',
            videoId: 'vid-env-301-haz-01',
            order: 1,
            title: 'Completing Form 10 Manifests & GPS Vehicle Verification',
            durationMinutes: 1,
            videoUrl: '/videos/env-form-10.mp4',
            description: 'Ensuring complete chain of custody documentation to prevent statutory penalty actions.',
          },
        ],
      },
    ],
    abilities: [
      {
        id: 'ab-env301-1',
        courseId: 'course-env-301',
        order: 1,
        code: '1.1',
        title: 'Hazardous Waste Storage & Transport Compliance',
        description: 'Executing compliant waste segregation, labeling, and statutory documentation.',
        videoDurationMinutes: 1,
        competencyAreaId: 'ca-env-reg',
      },
    ],
  },

  // =========================================================================
  // 6. OPERATION AND MAINTENANCE (O&M) - 4 COURSES
  // =========================================================================
  {
    id: 'course-om-101',
    courseId: 'course-om-101',
    code: 'OM-101',
    title: 'Industrial Pump Alignment, Mechanical Seals & Vibration Analysis',
    section: 'Operation and Maintenance (O&M)',
    category: 'Operation and Maintenance (O&M)',
    department: 'Plant Maintenance & Reliability',
    jobCategoryId: 'jc-om-tech',
    description:
      'Centrifugal and progressive cavity pumps: reverse dial indicator / laser shaft alignment, cartridge mechanical seal installation with Plan 11/53A flush, cavitation diagnosis, and ISO vibration limits.',
    thumbnailUrl: '/courses/high_pressure_pumps.jpg',
    provider: 'Nectar Reliability Engineering Unit',
    rating: 4.9,
    reviewCount: 51,
    level: 'Intermediate',
    estimatedHours: 4.5,
    passThreshold: 75,
    modules: [
      {
        id: 'mod-om-101-align',
        moduleId: 'mod-om-101-align',
        order: 1,
        title: 'Laser Shaft Alignment & Soft Foot Elimination',
        description: 'Tolerances below 0.05 mm angularity and offset for 2900 RPM direct-coupled effluent transfer pumps.',
        videos: [
          {
            id: 'vid-om-101-al-01',
            videoId: 'vid-om-101-al-01',
            order: 1,
            title: 'Setting Up Laser Alignment Optics on Pump Coupling',
            durationMinutes: 1,
            videoUrl: '/videos/om-laser-alignment.mp4',
            description: 'Correcting horizontal and vertical shimming to eliminate thermal growth vibration.',
          },
        ],
      },
      {
        id: 'mod-om-101-seal',
        moduleId: 'mod-om-101-seal',
        order: 2,
        title: 'Single & Double Mechanical Seal Assembly Protocols',
        description: 'Silicon carbide vs carbon faces, gland ring tightening torque, and barrier fluid pressurization.',
        videos: [
          {
            id: 'vid-om-101-seal-01',
            videoId: 'vid-om-101-seal-01',
            order: 1,
            title: 'Replacing Cartridge Mechanical Seal on Slurry Pumps',
            durationMinutes: 1,
            videoUrl: '/videos/om-mechanical-seal.mp4',
            description: 'Preventing seal face dry-running during abrasive slurry sludge transfer operations.',
          },
        ],
      },
    ],
    abilities: [
      {
        id: 'ab-om101-1',
        courseId: 'course-om-101',
        order: 1,
        code: '1.1',
        title: 'Pump Alignment & Mechanical Seal Reliability',
        description: 'Eliminating premature bearing failure and hazardous fluid seal leaks.',
        videoDurationMinutes: 1,
        competencyAreaId: 'ca-om-pumps',
      },
    ],
  },
  {
    id: 'course-om-201',
    courseId: 'course-om-201',
    code: 'OM-201',
    title: 'Root Cause Failure Analysis (RCFA) for Water Plant Equipment',
    section: 'Operation and Maintenance (O&M)',
    category: 'Operation and Maintenance (O&M)',
    department: 'Plant Maintenance & Reliability',
    jobCategoryId: 'jc-om-tech',
    description:
      'Failure investigation methodology: 5-Whys, Ishikawa fishbone diagrams, bearing raceway spalling patterns, impeller cavitation pitting vs erosive wear, and corrective action documentation.',
    thumbnailUrl: '/courses/preventive_maintenance.jpg',
    provider: 'Nectar Reliability Engineering Unit',
    rating: 4.8,
    reviewCount: 34,
    level: 'Advanced',
    estimatedHours: 4.0,
    passThreshold: 75,
    modules: [
      {
        id: 'mod-om-201-rcfa',
        moduleId: 'mod-om-201-rcfa',
        order: 1,
        title: 'Metallurgical & Wear Pattern Diagnostics in Slurry Pumps',
        description: 'Differentiating between NPSH-induced cavitation pitting, corrosion fatigue, and particulate abrasion.',
        videos: [
          {
            id: 'vid-om-201-rc-01',
            videoId: 'vid-om-201-rc-01',
            order: 1,
            title: 'Dissecting Failed Bearing Assemblies & Grease Degradation',
            durationMinutes: 1,
            videoUrl: '/videos/om-rcfa-bearing.mp4',
            description: 'Identifying electrical fluting from VFD stray currents versus moisture contamination.',
          },
        ],
      },
    ],
    abilities: [
      {
        id: 'ab-om201-1',
        courseId: 'course-om-201',
        order: 1,
        code: '1.1',
        title: 'RCFA Investigation & Corrective Action Loops',
        description: 'Driving systematic plant mean-time-between-failures (MTBF) improvement.',
        videoDurationMinutes: 1,
        competencyAreaId: 'ca-om-rcfa',
      },
    ],
  },
  {
    id: 'course-om-202',
    courseId: 'course-om-202',
    code: 'OM-202',
    title: 'Electrical MCC Panels, VFD Operation & Preventive Maintenance',
    section: 'Operation and Maintenance (O&M)',
    category: 'Operation and Maintenance (O&M)',
    department: 'Plant Maintenance & Reliability',
    jobCategoryId: 'jc-om-tech',
    description:
      'Motor Control Centers (MCC): air circuit breakers (ACB), molded case breakers (MCCB), contactor thermal overload relays, Variable Frequency Drive (VFD) parameter tuning, and thermographic infrared audits.',
    thumbnailUrl: '/courses/electrical_loto.jpg',
    provider: 'Nectar Reliability Engineering Unit',
    rating: 4.8,
    reviewCount: 38,
    level: 'Intermediate',
    estimatedHours: 4.0,
    passThreshold: 70,
    modules: [
      {
        id: 'mod-om-202-mcc',
        moduleId: 'mod-om-202-mcc',
        order: 1,
        title: 'MCC Busbar Infrared Thermography & Contact Resistance',
        description: 'Identifying high-resistance hot spots on busbar joints before catastrophic flashover occurs.',
        videos: [
          {
            id: 'vid-om-202-ir-01',
            videoId: 'vid-om-202-ir-01',
            order: 1,
            title: 'Thermal Camera Scan on 415V MCC Feeder Terminals',
            durationMinutes: 1,
            videoUrl: '/videos/om-ir-scan.mp4',
            description: 'Evaluating Delta-T criteria and executing torque tightening on de-energized panels.',
          },
        ],
      },
    ],
    abilities: [
      {
        id: 'ab-om202-1',
        courseId: 'course-om-202',
        order: 1,
        code: '1.1',
        title: 'Electrical Panel Maintenance & VFD Fault Recovery',
        description: 'Diagnosing VFD over-current, under-voltage, and ground fault trip sequences.',
        videoDurationMinutes: 1,
        competencyAreaId: 'ca-om-elec',
      },
    ],
  },
  {
    id: 'course-om-301',
    courseId: 'course-om-301',
    code: 'OM-301',
    title: 'Plant Safety Protocols: LOTO, Confined Space Entry & Hazard Audits',
    section: 'Operation and Maintenance (O&M)',
    category: 'Operation and Maintenance (O&M)',
    department: 'Plant Maintenance & Reliability',
    jobCategoryId: 'jc-om-tech',
    description:
      'Industrial occupational health & safety: Lockout/Tagout (LOTO) energy isolation, confined space entry inside equalization tanks and clarifiers with 4-gas detectors (O2, H2S, CO, LEL), and chemical PPE.',
    thumbnailUrl: '/courses/confined_space.jpg',
    provider: 'Nectar Safety & Compliance Cell',
    rating: 5.0,
    reviewCount: 65,
    level: 'Foundation',
    estimatedHours: 3.5,
    passThreshold: 80,
    modules: [
      {
        id: 'mod-om-301-loto',
        moduleId: 'mod-om-301-loto',
        order: 1,
        title: 'Lockout / Tagout (LOTO) Seven-Step Electrical & Valve Isolation',
        description: 'Zero energy state verification, padlock color coding, and group lockout boxes.',
        videos: [
          {
            id: 'vid-om-301-lo-01',
            videoId: 'vid-om-301-lo-01',
            order: 1,
            title: 'Executing Physical LOTO on High-Voltage Motor Starters',
            durationMinutes: 1,
            videoUrl: '/videos/om-loto-procedure.mp4',
            description: 'Isolating MCC breaker, testing start pushbutton to verify zero potential, and applying personal padlocks.',
          },
        ],
      },
      {
        id: 'mod-om-301-conf',
        moduleId: 'mod-om-301-conf',
        order: 2,
        title: 'Confined Space Entry with 4-Gas Sniffer Testing',
        description: 'Multi-gas meter bump testing, calibration for hydrogen sulfide (H2S), and tripod rescue harness setup.',
        videos: [
          {
            id: 'vid-om-301-conf-01',
            videoId: 'vid-om-301-conf-01',
            order: 1,
            title: 'Pre-Entry Atmospheric Testing in Effluent Sump Tanks',
            durationMinutes: 1,
            videoUrl: '/videos/om-confined-space.mp4',
            description: 'Checking stratified gas levels at top, middle, and bottom before issuing Entry Permit.',
          },
        ],
      },
    ],
    abilities: [
      {
        id: 'ab-om301-1',
        courseId: 'course-om-301',
        order: 1,
        code: '1.1',
        title: 'LOTO Energy Isolation & Zero Energy Verification',
        description: 'Enforcing life-saving rules during plant turnaround and equipment overhaul.',
        videoDurationMinutes: 1,
        competencyAreaId: 'ca-om-safe',
      },
    ],
  },
];
