export const trainingSessionsSeed = [
  {
    id: 'sess-1',
    title: 'MBBR Bio-Carrier Maintenance & Microscopic Sludge Exam',
    type: 'classroom',
    scheduledBy: 'emp0123',
    scheduledByName: 'Anand Dakave',
    scheduledAt: '2026-10-02T10:00:00Z',
    venueOrLink: 'ETP Technical Conference Room & Lab',
    employeeIds: ['emp0126', 'emp0127', 'emp0129'],
    courseId: 'course-etp-101',
    status: 'scheduled',
  },
  {
    id: 'sess-2',
    title: 'Industrial RO CIP Chemical Descaling Practical Workshop',
    type: 'on_site',
    scheduledBy: 'emp0131',
    scheduledByName: 'Uday Patil',
    scheduledAt: '2026-10-05T14:00:00Z',
    venueOrLink: 'RO Plant Skid 2 — Bay 4',
    employeeIds: ['emp0134', 'emp0136', 'emp0135'],
    courseId: 'course-ops-301',
    status: 'scheduled',
  },
  {
    id: 'sess-3',
    title: 'Multiple Effect Evaporator (MEE) Vacuum Leak Detection Drill',
    type: 'on_site',
    scheduledBy: 'emp0139',
    scheduledByName: 'Sanjay Waghaskar',
    scheduledAt: '2026-10-08T11:00:00Z',
    venueOrLink: 'MEE Plant Ground Floor Control Deck',
    employeeIds: ['emp0142', 'emp0144', 'emp0143'],
    courseId: 'course-zld-301',
    status: 'scheduled',
  },
  {
    id: 'sess-4',
    title: 'Site Lockout / Tagout (LOTO) & Chemical PPE Protocol',
    type: 'classroom',
    scheduledBy: 'emp0125',
    scheduledByName: 'Neetesh Diwathe',
    scheduledAt: '2026-10-12T09:30:00Z',
    venueOrLink: 'Central Safety Training Auditorium',
    employeeIds: ['emp0128', 'emp0129', 'emp0137', 'emp0145', 'emp0146'],
    courseId: 'course-saf-203',
    status: 'scheduled',
  },
];
