export const trainingRecordsSeed = [
  {
    id: 'tr-etp-shilpa-ops301',
    employeeId: 'emp0126',
    employeeName: 'Shilpa Hotkar',
    courseId: 'course-ops-301',
    courseTitle: 'Industrial RO Membrane Operations & CIP Descaling',
    status: 'certified',
    progressPct: 100,
    overallScorePct: 94,
    enrolledAt: '2026-08-01T09:00:00Z',
    completedAt: '2026-08-25T16:00:00Z',
    abilityProgress: {
      'ab-ro-1': true,
      'ab-ro-2': true,
    },
    assessments: {
      skillMap: {
        scorePct: 92,
        conductedAt: '2026-08-10T11:00:00Z',
      },
      written: {
        scorePct: 95,
        conductedAt: '2026-08-18T10:00:00Z',
      },
      practical: {
        scorePct: 94,
        evaluatorId: 'emp0131',
        evaluatorName: 'Uday Patil',
        conductedAt: '2026-08-22T14:00:00Z',
        scores: [
          { abilityId: 'ab-ro-1', abilityTitle: 'Membrane Flushing & CIP Dosing', score: 7, remark: 'Flawless chemical calculation and CIP pump priming.' },
          { abilityId: 'ab-ro-2', abilityTitle: 'Permeate Flux & SDI Monitoring', score: 6, remark: 'Accurate SDI pad inspection and flux recording.' },
        ],
        generalNotes: 'Excellent hands-on operational technique on RO skid.',
      },
      oral: {
        scorePct: 95,
        evaluatorId: 'emp0131',
        evaluatorName: 'Uday Patil',
        conductedAt: '2026-08-25T11:00:00Z',
        scores: [
          { abilityId: 'ab-ro-1', abilityTitle: 'Membrane Fouling Diagnoses', score: 7, remark: 'Quick identification of silica scaling versus biofouling.' },
          { abilityId: 'ab-ro-2', abilityTitle: 'Emergency Shutdown Norms', score: 6, remark: 'Understands high differential pressure interlocks.' },
        ],
        interviewNotes: 'Candidate articulated CIP chemical safety and CPCB discharge guidelines with high confidence.',
      },
    },
    certificateId: 'cert-shilpa-ro',
    certificateNo: 'NEIPL-WTP-RO-2026-0042',
    learningNeed: {
      competencyAreaId: 'ca-etp-bio',
      competencyAreaName: 'Biological Aeration & MBR Filtration',
      currentLevel: 'HIGH',
      trainingRequired: false,
      aiInsight: 'Demonstrates consistent control of DO and MLSS levels. Ready for final field viva sign-off.',
    },
  },
  {
    id: 'tr-etp-rohit-etp101',
    employeeId: 'emp0127',
    employeeName: 'Rohit Kumar Singh',
    courseId: 'course-etp-101',
    courseTitle: 'ETP Biological & Chemical Treatment Operations',
    status: 'in_progress',
    progressPct: 75,
    overallScorePct: 88,
    enrolledAt: '2026-09-01T08:30:00Z',
    abilityProgress: {
      'ab-1-1': true,
      'ab-1-2': true,
      'ab-1-3': false,
    },
    assessments: {
      skillMap: {
        scorePct: 86,
        conductedAt: '2026-09-12T10:00:00Z',
      },
      written: {
        scorePct: 88,
        conductedAt: '2026-09-20T11:00:00Z',
      },
      practical: {
        scorePct: 90,
        evaluatorId: 'emp0123',
        evaluatorName: 'Anand Dakave',
        conductedAt: '2026-09-24T15:30:00Z',
        scores: [
          { abilityId: 'ab-1-1', abilityTitle: 'Process Flow & HRT', score: 6, remark: 'Good grasp of equalization buffer limits.' },
          { abilityId: 'ab-1-2', abilityTitle: 'Coagulation & Jar Testing', score: 7, remark: 'Precise jar test dosing and flocculation observation.' },
          { abilityId: 'ab-1-3', abilityTitle: 'Aeration & Sludge SVI', score: 6, remark: 'Reliable DO meter calibration.' },
        ],
        generalNotes: 'Practical observation completed. Recommended for oral technical viva.',
      },
    },
    learningNeed: {
      competencyAreaId: 'ca-etp-chem',
      competencyAreaName: 'Physico-Chemical Coagulation & Sludge Press',
      currentLevel: 'MEDIUM',
      trainingRequired: true,
      aiInsight: 'Needs refresher on jar test chemical stoichiometry before final sign-off.',
    },
  },
  {
    id: 'tr-ro-siddhant-ops304',
    employeeId: 'emp0135',
    employeeName: 'Siddhant Marale',
    courseId: 'course-ops-304',
    courseTitle: 'Ultrafiltration (UF) Hollow-Fiber Membrane Backwash',
    status: 'certified',
    progressPct: 100,
    overallScorePct: 93,
    enrolledAt: '2026-07-15T09:00:00Z',
    completedAt: '2026-08-05T16:00:00Z',
    assessments: {
      skillMap: { scorePct: 92 },
      written: { scorePct: 94 },
      practical: { scorePct: 93, evaluatorId: 'emp0131', evaluatorName: 'Uday Patil' },
      oral: { scorePct: 93, evaluatorId: 'emp0131', evaluatorName: 'Uday Patil' },
    },
    certificateId: 'cert-siddhant-uf',
    certificateNo: 'NEIPL-WTP-UF-2026-0115',
  },
  {
    id: 'tr-mee-bhairavi-zld302',
    employeeId: 'emp0143',
    employeeName: 'Bhairavi Kadu',
    courseId: 'course-zld-302',
    courseTitle: 'Agitated Thin Film Dryer (ATFD) Salt Crystallization',
    status: 'certified',
    progressPct: 100,
    overallScorePct: 92,
    enrolledAt: '2026-07-01T09:00:00Z',
    completedAt: '2026-07-26T16:00:00Z',
    assessments: {
      skillMap: { scorePct: 90 },
      written: { scorePct: 92 },
      practical: { scorePct: 94, evaluatorId: 'emp0139', evaluatorName: 'Sanjay Waghaskar' },
      oral: { scorePct: 92, evaluatorId: 'emp0139', evaluatorName: 'Sanjay Waghaskar' },
    },
    certificateId: 'cert-bhairavi-atfd',
    certificateNo: 'NEIPL-ZLD-ATFD-2026-0204',
  },
  {
    id: 'tr-etp-mohee-saf202',
    employeeId: 'emp0128',
    employeeName: 'Mohee Vinchu',
    courseId: 'course-saf-202',
    courseTitle: 'Hazardous Chemical Handling & Spillage Emergency Response',
    status: 'certified',
    progressPct: 100,
    overallScorePct: 91,
    enrolledAt: '2026-07-05T09:00:00Z',
    completedAt: '2026-07-28T16:00:00Z',
    assessments: {
      skillMap: { scorePct: 90 },
      written: { scorePct: 92 },
      practical: { scorePct: 90, evaluatorId: 'emp0123', evaluatorName: 'Anand Dakave' },
      oral: { scorePct: 92, evaluatorId: 'emp0123', evaluatorName: 'Anand Dakave' },
    },
    certificateId: 'cert-mohee-saf',
    certificateNo: 'NEIPL-SAF-2026-0081',
  },
  {
    id: 'tr-hq-swati-saf203',
    employeeId: 'emp0147',
    employeeName: 'Swati Ingle',
    courseId: 'course-saf-203',
    courseTitle: 'EHS Statutory Compliance & Environmental Governance',
    status: 'certified',
    progressPct: 100,
    overallScorePct: 96,
    enrolledAt: '2026-05-01T09:00:00Z',
    completedAt: '2026-05-28T16:00:00Z',
    assessments: {
      skillMap: { scorePct: 98 },
      written: { scorePct: 95 },
      practical: { scorePct: 96 },
      oral: { scorePct: 96 },
    },
    certificateId: 'cert-swati-hr',
    certificateNo: 'NEIPL-HQ-HR-2026-0101',
  },
];
