export const employeesSeed = [
  // ETP Plant (s-etp)
  {
    id: 'emp0123',
    employeeId: 'emp0123',
    name: 'Anand Dakave',
    role: 'ETP Plant Manager',
    siteId: 's-etp',
    skillScore: 94,
    trainingStatus: 'compliant',
    email: 'etp.manager@nectarenviro.com',
    phone: '+91 98201 11001',
    joinedAt: '2019-04-01',
    yearsExperience: 14,
    department: 'Operations',
    designation: 'ETP Plant Manager',
    shiftId: 'sh-general',
    employmentStatus: 'active',
    employeeType: 'permanent',
    otEligible: false,
    payCategory: 'lead',
    employeeCategory: 'manager',
  },
  {
    id: 'emp0124',
    employeeId: 'emp0124',
    name: 'Bidhichand Rajbhar',
    role: 'Shift In-Charge',
    siteId: 's-etp',
    skillScore: 88,
    trainingStatus: 'compliant',
    email: 'etp.shift@nectarenviro.com',
    phone: '+91 98201 11002',
    joinedAt: '2020-06-15',
    yearsExperience: 10,
    department: 'Operations',
    designation: 'Shift In-Charge',
    shiftId: 'sh-general',
    employmentStatus: 'active',
    employeeType: 'permanent',
    otEligible: true,
    payCategory: 'lead',
    employeeCategory: 'shift_incharge',
    reportsToEmployeeId: 'emp0123',
    managerId: 'emp0123',
  },
  {
    id: 'emp0125',
    employeeId: 'emp0125',
    name: 'Neetesh Diwathe',
    role: 'Supervisor',
    siteId: 's-etp',
    skillScore: 86,
    trainingStatus: 'compliant',
    email: 'etp.supervisor@nectarenviro.com',
    phone: '+91 98201 11003',
    joinedAt: '2021-02-10',
    yearsExperience: 8,
    department: 'Operations',
    designation: 'Supervisor',
    shiftId: 'sh-general',
    employmentStatus: 'active',
    employeeType: 'permanent',
    otEligible: true,
    payCategory: 'supervisor',
    employeeCategory: 'supervisor',
    reportsToEmployeeId: 'emp0123',
    managerId: 'emp0123',
    shiftInChargeId: 'emp0124',
  },
  {
    id: 'emp0126',
    employeeId: 'emp0126',
    name: 'Shilpa Hotkar',
    role: 'Shift Employee',
    siteId: 's-etp',
    skillScore: 78,
    trainingStatus: 'compliant',
    email: 'shilpa.hotkar@nectarenviro.com',
    phone: '+91 98201 11004',
    joinedAt: '2022-01-15',
    yearsExperience: 3,
    department: 'Operations',
    designation: 'Plant Operator',
    shiftId: 'sh-morning',
    employmentStatus: 'active',
    employeeType: 'deputed',
    otEligible: true,
    payCategory: 'operator',
    employeeCategory: 'shift',
    reportsToEmployeeId: 'emp0125',
    managerId: 'emp0123',
    shiftInChargeId: 'emp0124',
    supervisorId: 'emp0125',
  },
  {
    id: 'emp0127',
    employeeId: 'emp0127',
    name: 'Rohit Kumar Singh',
    role: 'Shift Employee',
    siteId: 's-etp',
    skillScore: 84,
    trainingStatus: 'due-soon',
    email: 'rohit.singh@nectarenviro.com',
    phone: '+91 98201 11005',
    joinedAt: '2023-02-15',
    yearsExperience: 4,
    department: 'Operations',
    designation: 'Plant Operator',
    shiftId: 'sh-afternoon',
    employmentStatus: 'active',
    employeeType: 'deputed',
    otEligible: true,
    payCategory: 'operator',
    employeeCategory: 'shift',
    reportsToEmployeeId: 'emp0125',
    managerId: 'emp0123',
    shiftInChargeId: 'emp0124',
    supervisorId: 'emp0125',
  },
  {
    id: 'emp0128',
    employeeId: 'emp0128',
    name: 'Mohee Vinchu',
    role: 'Shift Employee',
    siteId: 's-etp',
    skillScore: 72,
    trainingStatus: 'overdue',
    email: 'mohee.vinchu@nectarenviro.com',
    phone: '+91 98201 11006',
    joinedAt: '2024-03-15',
    yearsExperience: 5,
    department: 'Operations',
    designation: 'Plant Operator',
    shiftId: 'sh-night',
    employmentStatus: 'active',
    employeeType: 'deputed',
    otEligible: true,
    payCategory: 'operator',
    employeeCategory: 'shift',
    reportsToEmployeeId: 'emp0125',
    managerId: 'emp0123',
    shiftInChargeId: 'emp0124',
    supervisorId: 'emp0125',
  },
  {
    id: 'emp0129',
    employeeId: 'emp0129',
    name: 'Sanket Jagadale',
    role: 'Shift Employee',
    siteId: 's-etp',
    skillScore: 81,
    trainingStatus: 'compliant',
    email: 'sanket.jagadale@nectarenviro.com',
    phone: '+91 98201 11007',
    joinedAt: '2022-04-15',
    yearsExperience: 6,
    department: 'Operations',
    designation: 'Plant Operator',
    shiftId: 'sh-morning',
    employmentStatus: 'active',
    employeeType: 'deputed',
    otEligible: true,
    payCategory: 'operator',
    employeeCategory: 'shift',
    reportsToEmployeeId: 'emp0125',
    managerId: 'emp0123',
    shiftInChargeId: 'emp0124',
    supervisorId: 'emp0125',
  },
  {
    id: 'emp0130',
    employeeId: 'emp0130',
    name: 'Sandip Ohol',
    role: 'General Employee',
    siteId: 's-etp',
    skillScore: 80,
    trainingStatus: 'compliant',
    email: 'sandip.ohol@nectarenviro.com',
    phone: '+91 98201 11008',
    joinedAt: '2022-08-01',
    yearsExperience: 5,
    department: 'Operations',
    designation: 'General Shift Operator',
    shiftId: 'sh-general',
    employmentStatus: 'active',
    employeeType: 'deputed',
    otEligible: true,
    payCategory: 'operator',
    employeeCategory: 'general',
    reportsToEmployeeId: 'emp0125',
    managerId: 'emp0123',
    shiftInChargeId: 'emp0124',
    supervisorId: 'emp0125',
  },

  // RO Plant (s-ro)
  {
    id: 'emp0131',
    employeeId: 'emp0131',
    name: 'Uday Patil',
    role: 'RO Plant Manager',
    siteId: 's-ro',
    skillScore: 92,
    trainingStatus: 'compliant',
    email: 'ro.manager@nectarenviro.com',
    phone: '+91 98201 11009',
    joinedAt: '2019-06-01',
    yearsExperience: 13,
    department: 'Operations',
    designation: 'RO Plant Manager',
    shiftId: 'sh-general',
    employmentStatus: 'active',
    employeeType: 'permanent',
    otEligible: false,
    payCategory: 'lead',
    employeeCategory: 'manager',
  },
  {
    id: 'emp0132',
    employeeId: 'emp0132',
    name: 'Pawan Jagdhane',
    role: 'Shift In-Charge',
    siteId: 's-ro',
    skillScore: 87,
    trainingStatus: 'compliant',
    email: 'ro.shift@nectarenviro.com',
    phone: '+91 98201 11010',
    joinedAt: '2020-08-15',
    yearsExperience: 9,
    department: 'Operations',
    designation: 'Shift In-Charge',
    shiftId: 'sh-general',
    employmentStatus: 'active',
    employeeType: 'permanent',
    otEligible: true,
    payCategory: 'lead',
    employeeCategory: 'shift_incharge',
    reportsToEmployeeId: 'emp0131',
    managerId: 'emp0131',
  },
  {
    id: 'emp0133',
    employeeId: 'emp0133',
    name: 'Vikas Dabade',
    role: 'Supervisor',
    siteId: 's-ro',
    skillScore: 85,
    trainingStatus: 'compliant',
    email: 'ro.supervisor@nectarenviro.com',
    phone: '+91 98201 11011',
    joinedAt: '2021-04-10',
    yearsExperience: 7,
    department: 'Operations',
    designation: 'Supervisor',
    shiftId: 'sh-general',
    employmentStatus: 'active',
    employeeType: 'permanent',
    otEligible: true,
    payCategory: 'supervisor',
    employeeCategory: 'supervisor',
    reportsToEmployeeId: 'emp0131',
    managerId: 'emp0131',
    shiftInChargeId: 'emp0132',
  },
  {
    id: 'emp0134',
    employeeId: 'emp0134',
    name: 'Rafik Shaikh',
    role: 'Shift Employee',
    siteId: 's-ro',
    skillScore: 76,
    trainingStatus: 'compliant',
    email: 'rafik.shaikh@nectarenviro.com',
    phone: '+91 98201 11012',
    joinedAt: '2022-03-15',
    yearsExperience: 4,
    department: 'Operations',
    designation: 'Plant Operator',
    shiftId: 'sh-morning',
    employmentStatus: 'active',
    employeeType: 'deputed',
    otEligible: true,
    payCategory: 'operator',
    employeeCategory: 'shift',
    reportsToEmployeeId: 'emp0133',
    managerId: 'emp0131',
    shiftInChargeId: 'emp0132',
    supervisorId: 'emp0133',
  },
  {
    id: 'emp0135',
    employeeId: 'emp0135',
    name: 'Siddhant Marale',
    role: 'Shift Employee',
    siteId: 's-ro',
    skillScore: 82,
    trainingStatus: 'due-soon',
    email: 'siddhant.marale@nectarenviro.com',
    phone: '+91 98201 11013',
    joinedAt: '2023-05-15',
    yearsExperience: 3,
    department: 'Operations',
    designation: 'Plant Operator',
    shiftId: 'sh-afternoon',
    employmentStatus: 'active',
    employeeType: 'deputed',
    otEligible: true,
    payCategory: 'operator',
    employeeCategory: 'shift',
    reportsToEmployeeId: 'emp0133',
    managerId: 'emp0131',
    shiftInChargeId: 'emp0132',
    supervisorId: 'emp0133',
  },
  {
    id: 'emp0136',
    employeeId: 'emp0136',
    name: 'Surekha Sitaram Bhosale',
    role: 'Shift Employee',
    siteId: 's-ro',
    skillScore: 74,
    trainingStatus: 'overdue',
    email: 'surekha.bhosale@nectarenviro.com',
    phone: '+91 98201 11014',
    joinedAt: '2024-01-15',
    yearsExperience: 2,
    department: 'Operations',
    designation: 'Plant Operator',
    shiftId: 'sh-night',
    employmentStatus: 'active',
    employeeType: 'deputed',
    otEligible: true,
    payCategory: 'operator',
    employeeCategory: 'shift',
    reportsToEmployeeId: 'emp0133',
    managerId: 'emp0131',
    shiftInChargeId: 'emp0132',
    supervisorId: 'emp0133',
  },
  {
    id: 'emp0137',
    employeeId: 'emp0137',
    name: 'Akshay Bendkoli',
    role: 'Shift Employee',
    siteId: 's-ro',
    skillScore: 83,
    trainingStatus: 'compliant',
    email: 'akshay.bendkoli@nectarenviro.com',
    phone: '+91 98201 11015',
    joinedAt: '2022-07-15',
    yearsExperience: 5,
    department: 'Operations',
    designation: 'Plant Operator',
    shiftId: 'sh-morning',
    employmentStatus: 'active',
    employeeType: 'deputed',
    otEligible: true,
    payCategory: 'operator',
    employeeCategory: 'shift',
    reportsToEmployeeId: 'emp0133',
    managerId: 'emp0131',
    shiftInChargeId: 'emp0132',
    supervisorId: 'emp0133',
  },
  {
    id: 'emp0138',
    employeeId: 'emp0138',
    name: 'Pravin Chormule',
    role: 'General Employee',
    siteId: 's-ro',
    skillScore: 79,
    trainingStatus: 'compliant',
    email: 'pravin.chormule@nectarenviro.com',
    phone: '+91 98201 11016',
    joinedAt: '2022-09-01',
    yearsExperience: 4,
    department: 'Operations',
    designation: 'General Shift Operator',
    shiftId: 'sh-general',
    employmentStatus: 'active',
    employeeType: 'deputed',
    otEligible: true,
    payCategory: 'operator',
    employeeCategory: 'general',
    reportsToEmployeeId: 'emp0133',
    managerId: 'emp0131',
    shiftInChargeId: 'emp0132',
    supervisorId: 'emp0133',
  },

  // MEE Plant (s-mee)
  {
    id: 'emp0139',
    employeeId: 'emp0139',
    name: 'Sanjay Waghaskar',
    role: 'MEE Plant Manager',
    siteId: 's-mee',
    skillScore: 91,
    trainingStatus: 'compliant',
    email: 'mee.manager@nectarenviro.com',
    phone: '+91 98201 11017',
    joinedAt: '2019-08-01',
    yearsExperience: 15,
    department: 'Operations',
    designation: 'MEE Plant Manager',
    shiftId: 'sh-general',
    employmentStatus: 'active',
    employeeType: 'permanent',
    otEligible: false,
    payCategory: 'lead',
    employeeCategory: 'manager',
  },
  {
    id: 'emp0140',
    employeeId: 'emp0140',
    name: 'Gaurav Khandagale',
    role: 'Shift In-Charge',
    siteId: 's-mee',
    skillScore: 89,
    trainingStatus: 'compliant',
    email: 'mee.shift@nectarenviro.com',
    phone: '+91 98201 11018',
    joinedAt: '2020-10-15',
    yearsExperience: 8,
    department: 'Operations',
    designation: 'Shift In-Charge',
    shiftId: 'sh-general',
    employmentStatus: 'active',
    employeeType: 'permanent',
    otEligible: true,
    payCategory: 'lead',
    employeeCategory: 'shift_incharge',
    reportsToEmployeeId: 'emp0139',
    managerId: 'emp0139',
  },
  {
    id: 'emp0141',
    employeeId: 'emp0141',
    name: 'Rushikesh Pawar',
    role: 'Supervisor',
    siteId: 's-mee',
    skillScore: 84,
    trainingStatus: 'compliant',
    email: 'mee.supervisor@nectarenviro.com',
    phone: '+91 98201 11019',
    joinedAt: '2021-06-10',
    yearsExperience: 6,
    department: 'Operations',
    designation: 'Supervisor',
    shiftId: 'sh-general',
    employmentStatus: 'active',
    employeeType: 'permanent',
    otEligible: true,
    payCategory: 'supervisor',
    employeeCategory: 'supervisor',
    reportsToEmployeeId: 'emp0139',
    managerId: 'emp0139',
    shiftInChargeId: 'emp0140',
  },
  {
    id: 'emp0142',
    employeeId: 'emp0142',
    name: 'Abhinandan Sanjay Pawane',
    role: 'Shift Employee',
    siteId: 's-mee',
    skillScore: 75,
    trainingStatus: 'compliant',
    email: 'abhinandan.pawane@nectarenviro.com',
    phone: '+91 98201 11020',
    joinedAt: '2022-05-15',
    yearsExperience: 3,
    department: 'Operations',
    designation: 'Plant Operator',
    shiftId: 'sh-morning',
    employmentStatus: 'active',
    employeeType: 'deputed',
    otEligible: true,
    payCategory: 'operator',
    employeeCategory: 'shift',
    reportsToEmployeeId: 'emp0141',
    managerId: 'emp0139',
    shiftInChargeId: 'emp0140',
    supervisorId: 'emp0141',
  },
  {
    id: 'emp0143',
    employeeId: 'emp0143',
    name: 'Bhairavi Kadu',
    role: 'Shift Employee',
    siteId: 's-mee',
    skillScore: 80,
    trainingStatus: 'due-soon',
    email: 'bhairavi.kadu@nectarenviro.com',
    phone: '+91 98201 11021',
    joinedAt: '2023-08-15',
    yearsExperience: 2,
    department: 'Operations',
    designation: 'Plant Operator',
    shiftId: 'sh-afternoon',
    employmentStatus: 'active',
    employeeType: 'deputed',
    otEligible: true,
    payCategory: 'operator',
    employeeCategory: 'shift',
    reportsToEmployeeId: 'emp0141',
    managerId: 'emp0139',
    shiftInChargeId: 'emp0140',
    supervisorId: 'emp0141',
  },
  {
    id: 'emp0144',
    employeeId: 'emp0144',
    name: 'Meghal Salgaonkar',
    role: 'Shift Employee',
    siteId: 's-mee',
    skillScore: 71,
    trainingStatus: 'overdue',
    email: 'meghal.salgaonkar@nectarenviro.com',
    phone: '+91 98201 11022',
    joinedAt: '2024-02-15',
    yearsExperience: 2,
    department: 'Operations',
    designation: 'Plant Operator',
    shiftId: 'sh-night',
    employmentStatus: 'active',
    employeeType: 'deputed',
    otEligible: true,
    payCategory: 'operator',
    employeeCategory: 'shift',
    reportsToEmployeeId: 'emp0141',
    managerId: 'emp0139',
    shiftInChargeId: 'emp0140',
    supervisorId: 'emp0141',
  },
  {
    id: 'emp0145',
    employeeId: 'emp0145',
    name: 'Anita Kadam',
    role: 'Shift Employee',
    siteId: 's-mee',
    skillScore: 82,
    trainingStatus: 'compliant',
    email: 'anita.kadam@nectarenviro.com',
    phone: '+91 98201 11023',
    joinedAt: '2022-11-15',
    yearsExperience: 4,
    department: 'Operations',
    designation: 'Plant Operator',
    shiftId: 'sh-morning',
    employmentStatus: 'active',
    employeeType: 'deputed',
    otEligible: true,
    payCategory: 'operator',
    employeeCategory: 'shift',
    reportsToEmployeeId: 'emp0141',
    managerId: 'emp0139',
    shiftInChargeId: 'emp0140',
    supervisorId: 'emp0141',
  },
  {
    id: 'emp0146',
    employeeId: 'emp0146',
    name: 'Ravi Thakur',
    role: 'General Employee',
    siteId: 's-mee',
    skillScore: 78,
    trainingStatus: 'compliant',
    email: 'ravi.thakur@nectarenviro.com',
    phone: '+91 98201 11024',
    joinedAt: '2022-10-01',
    yearsExperience: 3,
    department: 'Operations',
    designation: 'General Shift Operator',
    shiftId: 'sh-general',
    employmentStatus: 'active',
    employeeType: 'deputed',
    otEligible: true,
    payCategory: 'operator',
    employeeCategory: 'general',
    reportsToEmployeeId: 'emp0141',
    managerId: 'emp0139',
    shiftInChargeId: 'emp0140',
    supervisorId: 'emp0141',
  },

  // Central HR (Swati Ingle)
  {
    id: 'emp0147',
    employeeId: 'emp0147',
    name: 'Swati Ingle',
    role: 'HR Manager',
    siteId: null,
    skillScore: 90,
    trainingStatus: 'compliant',
    email: 'hr@nectarenviro.com',
    phone: '+91 98201 11026',
    joinedAt: '2018-03-15',
    yearsExperience: 12,
    department: 'Human Resources',
    designation: 'Head of Human Resources',
    shiftId: 'sh-general',
    employmentStatus: 'active',
    employeeType: 'permanent',
    otEligible: false,
    payCategory: 'lead',
    employeeCategory: 'hr',
  },
];
