/** Demo leave requests — aligned with client/lib/leave/store.ts seed. */
export const leavesSeed = [
  {
    id: 'lv1',
    employeeId: 'emp0126',
    employeeName: 'Shilpa Hotkar',
    siteId: 's-etp',
    department: 'Operations',
    shiftId: 'sh-morning',
    mode: 'planned',
    leaveType: 'casual',
    status: 'REQUESTED',
    entrySource: 'employee',
    startDate: '2026-09-25',
    endDate: '2026-09-26',
    expectedReturnDate: '2026-09-27',
    reason: 'Family function',
    enteredByName: 'Shilpa Hotkar',
    enteredByRole: 'employee',
    supervisorName: 'Neetesh Diwathe',
    siteInChargeName: 'Bidhichand Rajbhar',
    managerName: 'Anand Dakave',
    replacementRequired: true,
    potentialOtHours: 0,
    potentialOtCost: 0,
    leaveBalanceDays: 8,
    daysRequested: 2,
    createdAt: '2026-09-20T10:00:00Z',
    updatedAt: '2026-09-20T10:00:00Z',
    timeline: [
      {
        at: '2026-09-20T10:00:00Z',
        actor: 'Shilpa Hotkar',
        role: 'employee',
        action: 'Leave requested',
        note: 'Planned leave submitted',
      },
    ],
  },
  {
    id: 'lv2',
    employeeId: 'emp0127',
    employeeName: 'Rohit Kumar Singh',
    siteId: 's-etp',
    department: 'Operations',
    shiftId: 'sh-afternoon',
    mode: 'planned',
    leaveType: 'sick',
    status: 'PENDING_EMPLOYEE_CONSENT',
    entrySource: 'supervisor_on_behalf',
    startDate: '2026-09-28',
    endDate: '2026-09-29',
    expectedReturnDate: '2026-09-30',
    reason: 'Medical appointment — employee asked supervisor to file',
    enteredByName: 'Neetesh Diwathe',
    enteredByRole: 'supervisor',
    supervisorName: 'Neetesh Diwathe',
    siteInChargeName: 'Bidhichand Rajbhar',
    managerName: 'Anand Dakave',
    replacementRequired: true,
    potentialOtHours: 0,
    potentialOtCost: 0,
    leaveBalanceDays: 6,
    daysRequested: 2,
    createdAt: '2026-09-22T09:00:00Z',
    updatedAt: '2026-09-22T09:00:00Z',
    timeline: [
      {
        at: '2026-09-22T09:00:00Z',
        actor: 'Neetesh Diwathe',
        role: 'supervisor',
        action: 'Leave submitted on behalf of employee',
        note: 'Awaiting employee consent',
      },
    ],
  },
  {
    id: 'lv3',
    employeeId: 'emp0134',
    employeeName: 'Rafik Shaikh',
    siteId: 's-ro',
    department: 'Operations',
    shiftId: 'sh-morning',
    mode: 'planned',
    leaveType: 'casual',
    status: 'REQUESTED',
    entrySource: 'supervisor_on_behalf',
    startDate: '2026-10-01',
    endDate: '2026-10-02',
    expectedReturnDate: '2026-10-03',
    reason: 'Personal work',
    enteredByName: 'Vikas Dabade',
    enteredByRole: 'supervisor',
    employeeConsent: 'approved',
    supervisorName: 'Vikas Dabade',
    siteInChargeName: 'Pawan Jagdhane',
    managerName: 'Uday Patil',
    replacementRequired: true,
    assignedRelieverId: 'rv2',
    replacementPlan: 'Cluster reliever Lata More assigned',
    potentialOtHours: 0,
    potentialOtCost: 0,
    leaveBalanceDays: 5,
    daysRequested: 2,
    createdAt: '2026-09-20T09:00:00Z',
    updatedAt: '2026-09-21T11:00:00Z',
    timeline: [
      {
        at: '2026-09-20T09:00:00Z',
        actor: 'Vikas Dabade',
        role: 'supervisor',
        action: 'Leave submitted on behalf',
      },
      {
        at: '2026-09-21T11:00:00Z',
        actor: 'Rafik Shaikh',
        role: 'employee',
        action: 'Employee consented',
        note: 'Approved to proceed to manager',
      },
    ],
  },
  {
    id: 'lv4',
    employeeId: 'emp0142',
    employeeName: 'Abhinandan Sanjay Pawane',
    siteId: 's-mee',
    department: 'Operations',
    shiftId: 'sh-morning',
    mode: 'emergency',
    leaveType: 'family_emergency',
    status: 'SUPERVISOR_RECORDED',
    entrySource: 'supervisor_on_behalf',
    startDate: '2026-09-23',
    endDate: '2026-09-24',
    expectedReturnDate: '2026-09-25',
    reason: 'Family emergency — informed verbally',
    enteredByName: 'Rushikesh Pawar',
    enteredByRole: 'supervisor',
    employeeConsent: 'approved',
    supervisorName: 'Rushikesh Pawar',
    siteInChargeName: 'Gaurav Khandagale',
    managerName: 'Sanjay Waghaskar',
    replacementRequired: true,
    potentialOtHours: 8,
    potentialOtCost: 2160,
    leaveBalanceDays: 2,
    daysRequested: 2,
    createdAt: '2026-09-23T07:20:00Z',
    updatedAt: '2026-09-23T07:20:00Z',
    timeline: [
      {
        at: '2026-09-23T07:20:00Z',
        actor: 'Rushikesh Pawar',
        role: 'supervisor',
        action: 'Emergency absence recorded',
      },
    ],
  },
  {
    id: 'lv5',
    employeeId: 'emp0130',
    employeeName: 'Sandip Ohol',
    siteId: 's-etp',
    department: 'Operations',
    shiftId: 'sh-general',
    mode: 'planned',
    leaveType: 'casual',
    status: 'APPROVED',
    entrySource: 'employee',
    startDate: '2026-09-15',
    endDate: '2026-09-16',
    expectedReturnDate: '2026-09-17',
    actualReturnDate: '2026-09-17',
    reason: 'Personal work',
    enteredByName: 'Sandip Ohol',
    enteredByRole: 'employee',
    supervisorName: 'Neetesh Diwathe',
    siteInChargeName: 'Bidhichand Rajbhar',
    managerName: 'Anand Dakave',
    managerDecision: 'approved',
    replacementRequired: false,
    potentialOtHours: 0,
    potentialOtCost: 0,
    leaveBalanceDays: 10,
    daysRequested: 2,
    createdAt: '2026-09-10T12:00:00Z',
    updatedAt: '2026-09-17T08:30:00Z',
    timeline: [
      {
        at: '2026-09-10T12:00:00Z',
        actor: 'Sandip Ohol',
        role: 'employee',
        action: 'Leave requested',
      },
      {
        at: '2026-09-11T10:00:00Z',
        actor: 'Anand Dakave',
        role: 'management',
        action: 'Manager approved',
        note: 'Manpower OK',
      },
    ],
  },
  {
    id: 'lv6',
    employeeId: 'emp0135',
    employeeName: 'Siddhant Marale',
    siteId: 's-ro',
    department: 'Operations',
    shiftId: 'sh-afternoon',
    mode: 'planned',
    leaveType: 'sick',
    status: 'REJECTED',
    entrySource: 'employee',
    startDate: '2026-09-20',
    endDate: '2026-09-22',
    expectedReturnDate: '2026-09-23',
    reason: 'Fever',
    enteredByName: 'Siddhant Marale',
    enteredByRole: 'employee',
    supervisorName: 'Vikas Dabade',
    siteInChargeName: 'Pawan Jagdhane',
    managerName: 'Uday Patil',
    managerDecision: 'rejected',
    rejectionReason: 'Critical RO maintenance window — reschedule after 25 Sep',
    replacementRequired: true,
    potentialOtHours: 0,
    potentialOtCost: 0,
    leaveBalanceDays: 3,
    daysRequested: 3,
    createdAt: '2026-09-19T11:00:00Z',
    updatedAt: '2026-09-19T15:00:00Z',
    timeline: [
      {
        at: '2026-09-19T11:00:00Z',
        actor: 'Siddhant Marale',
        role: 'employee',
        action: 'Leave requested',
      },
      {
        at: '2026-09-19T15:00:00Z',
        actor: 'Uday Patil',
        role: 'management',
        action: 'Manager rejected',
        note: 'Critical RO maintenance window — reschedule after 25 Sep',
      },
    ],
  },
  {
    id: 'lv7',
    employeeId: 'emp0143',
    employeeName: 'Bhairavi Kadu',
    siteId: 's-mee',
    department: 'Operations',
    shiftId: 'sh-afternoon',
    mode: 'planned',
    leaveType: 'casual',
    status: 'REJECTED',
    entrySource: 'supervisor_on_behalf',
    startDate: '2026-09-26',
    endDate: '2026-09-26',
    expectedReturnDate: '2026-09-27',
    reason: 'Personal errand',
    enteredByName: 'Rushikesh Pawar',
    enteredByRole: 'supervisor',
    employeeConsent: 'rejected',
    rejectionReason: 'Employee rejected consent',
    supervisorName: 'Rushikesh Pawar',
    siteInChargeName: 'Gaurav Khandagale',
    managerName: 'Sanjay Waghaskar',
    replacementRequired: false,
    potentialOtHours: 0,
    potentialOtCost: 0,
    leaveBalanceDays: 7,
    daysRequested: 1,
    createdAt: '2026-09-22T10:00:00Z',
    updatedAt: '2026-09-22T14:00:00Z',
    timeline: [
      {
        at: '2026-09-22T10:00:00Z',
        actor: 'Rushikesh Pawar',
        role: 'supervisor',
        action: 'Leave submitted on behalf',
      },
      {
        at: '2026-09-22T14:00:00Z',
        actor: 'Bhairavi Kadu',
        role: 'employee',
        action: 'Employee rejected consent',
        note: 'I did not ask for leave — please cancel',
      },
    ],
  },
];
