export const relieversSeed = [
  {
    id: 'rv1',
    name: 'Sanjay Kamble',
    phone: '+91 98765 22001',
    clusterId: 'c-demo',
    homeSiteId: 's-etp',
    skills: ['ETP Ops', 'Safety', 'General Shift'],
    plantTypes: ['ETP'],
    availability: 'available',
  },
  {
    id: 'rv2',
    name: 'Lata More',
    phone: '+91 98765 22002',
    clusterId: 'c-demo',
    homeSiteId: 's-ro',
    skills: ['RO Ops', 'Sampling', 'Safety'],
    plantTypes: ['RO'],
    availability: 'available',
  },
  {
    id: 'rv3',
    name: 'Deepak Salve',
    phone: '+91 98765 22003',
    clusterId: 'c-demo',
    skills: ['ETP Ops', 'MEE Ops', 'Maintenance'],
    plantTypes: ['ETP', 'MEE'],
    availability: 'available',
  },
  {
    id: 'rv4',
    name: 'Rina Pawaskar',
    phone: '+91 98765 22004',
    clusterId: 'c-demo',
    homeSiteId: 's-ro',
    skills: ['RO Ops', 'Safety', 'General Shift'],
    plantTypes: ['RO'],
    availability: 'assigned',
    assignedSiteId: 's-ro',
    assignedAbsenceId: 'ab2',
  },
  {
    id: 'rv5',
    name: 'Yogesh Kale',
    phone: '+91 98765 22005',
    clusterId: 'c-demo',
    homeSiteId: 's-mee',
    skills: ['MEE Ops', 'Sampling', 'Safety'],
    plantTypes: ['MEE'],
    availability: 'available',
  },
  {
    id: 'rv6',
    name: 'Nitin Jadhav',
    phone: '+91 98765 22006',
    clusterId: 'c-demo',
    homeSiteId: 's-mee',
    skills: ['MEE Ops', 'Maintenance', 'General Shift'],
    plantTypes: ['MEE'],
    availability: 'unavailable',
  },
  {
    id: 'rv7',
    employeeId: 'emp0127',
    name: 'Rohit Kumar Singh',
    phone: '+91 98201 11005',
    clusterId: 'c-demo',
    homeSiteId: 's-etp',
    skills: ['ETP Ops', 'Safety'],
    plantTypes: ['ETP'],
    availability: 'available',
  },
];

export const relieverAbsencesSeed = [
  {
    id: 'ab1',
    employeeId: 'emp0126',
    employeeName: 'Shilpa Hotkar',
    siteId: 's-etp',
    clusterId: 'c-demo',
    date: '2026-09-23',
    shiftId: 'sh-morning',
    reason: 'Sudden leave',
    requiredSkills: ['ETP Ops', 'Safety'],
    status: 'open',
  },
  {
    id: 'ab2',
    employeeId: 'emp0134',
    employeeName: 'Rafik Shaikh',
    siteId: 's-ro',
    clusterId: 'c-demo',
    date: '2026-09-23',
    shiftId: 'sh-night',
    reason: 'Medical',
    requiredSkills: ['RO Ops', 'Safety'],
    status: 'pool_assigned',
    assignedRelieverId: 'rv4',
    resolutionNote: 'Cluster reliever Rina Pawaskar assigned',
  },
  {
    id: 'ab3',
    employeeId: 'emp0144',
    employeeName: 'Meghal Salgaonkar',
    siteId: 's-mee',
    clusterId: 'c-demo',
    date: '2026-09-22',
    shiftId: 'sh-morning',
    reason: 'Weekly-off clash',
    requiredSkills: ['MEE Ops'],
    status: 'ot_fallback',
    resolutionNote: 'No available pool match — OT authorized as last resort',
  },
  {
    id: 'ab4',
    employeeId: 'emp0128',
    employeeName: 'Mohee Vinchu',
    siteId: 's-etp',
    clusterId: 'c-demo',
    date: '2026-09-23',
    shiftId: 'sh-night',
    reason: 'Travel delay',
    requiredSkills: ['ETP Ops', 'Maintenance'],
    status: 'open',
  },
];
