export const shiftsSeed = [
  {
    id: 'rp1',
    siteId: 's-etp',
    fromDate: '2026-09-24',
    toDate: '2026-09-30',
    employeesAffected: 3,
    fromCode: 'A',
    toCode: 'B',
    status: 'pending_manager',
    label: 'ETP Rotation Cycle 38 (A -> B)',
    assignments: [
      { employeeId: 'emp0126', employeeName: 'Shilpa Hotkar', date: '2026-09-24', code: 'A', shiftId: 'sh-morning' },
      { employeeId: 'emp0127', employeeName: 'Rohit Kumar Singh', date: '2026-09-24', code: 'B', shiftId: 'sh-afternoon' },
      { employeeId: 'emp0128', employeeName: 'Mohee Vinchu', date: '2026-09-24', code: 'C', shiftId: 'sh-night' },
      { employeeId: 'emp0130', employeeName: 'Sandip Ohol', date: '2026-09-24', code: 'G', shiftId: 'sh-general' },
    ],
    changeRequests: [
      {
        id: 'scr1',
        employeeId: 'emp0127',
        employeeName: 'Rohit Kumar Singh',
        siteId: 's-etp',
        date: '2026-09-28',
        fromShiftId: 'sh-afternoon',
        toShiftId: 'sh-night',
        reason: 'Replacement required due to absence',
        requestedBy: 'Neetesh Diwathe',
        status: 'PENDING',
        potentialOtHours: 0,
        manpowerOk: true,
        createdAt: '2026-09-22T10:00:00Z',
      },
    ],
  },
  {
    id: 'rp2',
    siteId: 's-ro',
    fromDate: '2026-09-25',
    toDate: '2026-10-01',
    employeesAffected: 2,
    fromCode: 'B',
    toCode: 'C',
    status: 'pending_manager',
    label: 'RO Rotation Cycle 38 (B -> C)',
    assignments: [
      { employeeId: 'emp0134', employeeName: 'Rafik Shaikh', date: '2026-09-25', code: 'A', shiftId: 'sh-morning' },
      { employeeId: 'emp0135', employeeName: 'Siddhant Marale', date: '2026-09-25', code: 'B', shiftId: 'sh-afternoon' },
      { employeeId: 'emp0136', employeeName: 'Surekha Sitaram Bhosale', date: '2026-09-25', code: 'C', shiftId: 'sh-night' },
      { employeeId: 'emp0138', employeeName: 'Pravin Chormule', date: '2026-09-25', code: 'G', shiftId: 'sh-general' },
    ],
    changeRequests: [
      {
        id: 'scr2',
        employeeId: 'emp0134',
        employeeName: 'Rafik Shaikh',
        siteId: 's-ro',
        date: '2026-09-24',
        fromShiftId: 'sh-night',
        toShiftId: 'sh-morning',
        reason: 'Personal constraint',
        requestedBy: 'Vikas Dabade',
        status: 'PENDING',
        potentialOtHours: 8,
        manpowerOk: false,
        createdAt: '2026-09-21T14:00:00Z',
      },
    ],
  },
  {
    id: 'rp3',
    siteId: 's-mee',
    fromDate: '2026-09-26',
    toDate: '2026-10-02',
    employeesAffected: 1,
    fromCode: 'C',
    toCode: 'A',
    status: 'draft',
    label: 'MEE Rotation Cycle 38 (C -> A)',
    assignments: [
      { employeeId: 'emp0142', employeeName: 'Abhinandan Sanjay Pawane', date: '2026-09-26', code: 'A', shiftId: 'sh-morning' },
      { employeeId: 'emp0143', employeeName: 'Bhairavi Kadu', date: '2026-09-26', code: 'B', shiftId: 'sh-afternoon' },
      { employeeId: 'emp0144', employeeName: 'Meghal Salgaonkar', date: '2026-09-26', code: 'C', shiftId: 'sh-night' },
      { employeeId: 'emp0146', employeeName: 'Ravi Thakur', date: '2026-09-26', code: 'G', shiftId: 'sh-general' },
    ],
    changeRequests: [],
  },
];
