export const sitesSeed = [
  {
    id: 's-etp',
    siteId: 's-etp',
    name: 'ETP Plant',
    plantType: 'ETP',
    location: 'Thane, MH',
    headcount: 8,
    readiness: 94,
    managerId: 'emp0123',
    managerName: 'Anand Dakave',
    managerEmail: 'etp.manager@nectarenviro.com',
  },
  {
    id: 's-ro',
    siteId: 's-ro',
    name: 'RO Plant',
    plantType: 'RO',
    location: 'Pune, MH',
    headcount: 8,
    readiness: 92,
    managerId: 'emp0131',
    managerName: 'Uday Patil',
    managerEmail: 'ro.manager@nectarenviro.com',
  },
  {
    id: 's-mee',
    siteId: 's-mee',
    name: 'MEE Plant',
    plantType: 'MEE',
    location: 'Vashi, MH',
    headcount: 8,
    readiness: 88,
    managerId: 'emp0139',
    managerName: 'Sanjay Waghaskar',
    managerEmail: 'mee.manager@nectarenviro.com',
  },
];
