export const sitesSeed = [
  {
    id: 's-etp',
    siteId: 's-etp',
    name: 'Nectar Enviro, Thane',
    plantType: 'ETP',
    plantTypes: ['ETP', 'STP', 'WTP', 'RO'],
    location: 'Thane, MH',
    headcount: 8,
    readiness: 94,
    managerId: 'emp0123',
    managerName: 'Anand Dakave',
    managerEmail: 'etp.manager@nectarenviro.com',
    status: 'operational',
  },
  {
    id: 's-ro',
    siteId: 's-ro',
    name: 'Nectar Enviro, Pune',
    plantType: 'RO',
    plantTypes: ['MEE', 'WTP'],
    location: 'Pune, MH',
    headcount: 8,
    readiness: 92,
    managerId: 'emp0131',
    managerName: 'Uday Patil',
    managerEmail: 'ro.manager@nectarenviro.com',
    status: 'operational',
  },
  {
    id: 's-mee',
    siteId: 's-mee',
    name: 'Nectar Enviro, Vashi',
    plantType: 'MEE',
    plantTypes: ['MEE', 'STP', 'RO'],
    location: 'Vashi, MH',
    headcount: 8,
    readiness: 88,
    managerId: 'emp0139',
    managerName: 'Sanjay Waghaskar',
    managerEmail: 'mee.manager@nectarenviro.com',
    status: 'operational',
  },
];
