/**
 * Demo login accounts — mirrors client/lib/auth.ts DEMO_USERS (+ hidden).
 * Shared password: nectar2026
 */

export type UserSeed = {
  email: string;
  password: string;
  name: string;
  role: string;
  siteId?: string;
  employeeId?: string;
  visibleOnLogin: boolean;
  active: boolean;
};

import { hodUsersSeed } from './e-permit.seed';

const P = 'nectar2026';

export const usersSeed: UserSeed[] = [
  {
    email: 'director@nectarenviro.com',
    password: P,
    name: 'Prashant Rohidas Adsul',
    role: 'director',
    visibleOnLogin: true,
    active: true,
  },
  {
    email: 'hr@nectarenviro.com',
    password: P,
    name: 'Swati Ingle',
    role: 'hr',
    employeeId: 'emp0147',
    visibleOnLogin: true,
    active: true,
  },
  // ETP
  {
    email: 'etp.manager@nectarenviro.com',
    password: P,
    name: 'Anand Dakave',
    role: 'manager',
    siteId: 's-etp',
    employeeId: 'emp0123',
    visibleOnLogin: true,
    active: true,
  },
  {
    email: 'etp.shift@nectarenviro.com',
    password: P,
    name: 'Bidhichand Rajbhar',
    role: 'shift_incharge',
    siteId: 's-etp',
    employeeId: 'emp0124',
    visibleOnLogin: true,
    active: true,
  },
  {
    email: 'etp.supervisor@nectarenviro.com',
    password: P,
    name: 'Neetesh Diwathe',
    role: 'supervisor',
    siteId: 's-etp',
    employeeId: 'emp0125',
    visibleOnLogin: true,
    active: true,
  },
  {
    email: 'shilpa.hotkar@nectarenviro.com',
    password: P,
    name: 'Shilpa Hotkar',
    role: 'employee',
    siteId: 's-etp',
    employeeId: 'emp0126',
    visibleOnLogin: true,
    active: true,
  },
  {
    email: 'rohit.singh@nectarenviro.com',
    password: P,
    name: 'Rohit Kumar Singh',
    role: 'employee',
    siteId: 's-etp',
    employeeId: 'emp0127',
    visibleOnLogin: true,
    active: true,
  },
  {
    email: 'mohee.vinchu@nectarenviro.com',
    password: P,
    name: 'Mohee Vinchu',
    role: 'employee',
    siteId: 's-etp',
    employeeId: 'emp0128',
    visibleOnLogin: true,
    active: true,
  },
  {
    email: 'sanket.jagadale@nectarenviro.com',
    password: P,
    name: 'Sanket Jagadale',
    role: 'employee',
    siteId: 's-etp',
    employeeId: 'emp0129',
    visibleOnLogin: true,
    active: true,
  },
  {
    email: 'sandip.ohol@nectarenviro.com',
    password: P,
    name: 'Sandip Ohol',
    role: 'employee',
    siteId: 's-etp',
    employeeId: 'emp0130',
    visibleOnLogin: true,
    active: true,
  },
  // RO
  {
    email: 'ro.manager@nectarenviro.com',
    password: P,
    name: 'Uday Patil',
    role: 'manager',
    siteId: 's-ro',
    employeeId: 'emp0131',
    visibleOnLogin: true,
    active: true,
  },
  {
    email: 'ro.shift@nectarenviro.com',
    password: P,
    name: 'Pawan Jagdhane',
    role: 'shift_incharge',
    siteId: 's-ro',
    employeeId: 'emp0132',
    visibleOnLogin: true,
    active: true,
  },
  {
    email: 'ro.supervisor@nectarenviro.com',
    password: P,
    name: 'Vikas Dabade',
    role: 'supervisor',
    siteId: 's-ro',
    employeeId: 'emp0133',
    visibleOnLogin: true,
    active: true,
  },
  {
    email: 'rafik.shaikh@nectarenviro.com',
    password: P,
    name: 'Rafik Shaikh',
    role: 'employee',
    siteId: 's-ro',
    employeeId: 'emp0134',
    visibleOnLogin: true,
    active: true,
  },
  {
    email: 'siddhant.marale@nectarenviro.com',
    password: P,
    name: 'Siddhant Marale',
    role: 'employee',
    siteId: 's-ro',
    employeeId: 'emp0135',
    visibleOnLogin: true,
    active: true,
  },
  {
    email: 'surekha.bhosale@nectarenviro.com',
    password: P,
    name: 'Surekha Sitaram Bhosale',
    role: 'employee',
    siteId: 's-ro',
    employeeId: 'emp0136',
    visibleOnLogin: true,
    active: true,
  },
  {
    email: 'akshay.bendkoli@nectarenviro.com',
    password: P,
    name: 'Akshay Bendkoli',
    role: 'employee',
    siteId: 's-ro',
    employeeId: 'emp0137',
    visibleOnLogin: true,
    active: true,
  },
  {
    email: 'pravin.chormule@nectarenviro.com',
    password: P,
    name: 'Pravin Chormule',
    role: 'employee',
    siteId: 's-ro',
    employeeId: 'emp0138',
    visibleOnLogin: true,
    active: true,
  },
  // MEE
  {
    email: 'mee.manager@nectarenviro.com',
    password: P,
    name: 'Sanjay Waghaskar',
    role: 'manager',
    siteId: 's-mee',
    employeeId: 'emp0139',
    visibleOnLogin: true,
    active: true,
  },
  {
    email: 'mee.shift@nectarenviro.com',
    password: P,
    name: 'Gaurav Khandagale',
    role: 'shift_incharge',
    siteId: 's-mee',
    employeeId: 'emp0140',
    visibleOnLogin: true,
    active: true,
  },
  {
    email: 'mee.supervisor@nectarenviro.com',
    password: P,
    name: 'Rushikesh Pawar',
    role: 'supervisor',
    siteId: 's-mee',
    employeeId: 'emp0141',
    visibleOnLogin: true,
    active: true,
  },
  {
    email: 'abhinandan.pawane@nectarenviro.com',
    password: P,
    name: 'Abhinandan Sanjay Pawane',
    role: 'employee',
    siteId: 's-mee',
    employeeId: 'emp0142',
    visibleOnLogin: true,
    active: true,
  },
  {
    email: 'bhairavi.kadu@nectarenviro.com',
    password: P,
    name: 'Bhairavi Kadu',
    role: 'employee',
    siteId: 's-mee',
    employeeId: 'emp0143',
    visibleOnLogin: true,
    active: true,
  },
  {
    email: 'meghal.salgaonkar@nectarenviro.com',
    password: P,
    name: 'Meghal Salgaonkar',
    role: 'employee',
    siteId: 's-mee',
    employeeId: 'emp0144',
    visibleOnLogin: true,
    active: true,
  },
  {
    email: 'anita.kadam@nectarenviro.com',
    password: P,
    name: 'Anita Kadam',
    role: 'employee',
    siteId: 's-mee',
    employeeId: 'emp0145',
    visibleOnLogin: true,
    active: true,
  },
  {
    email: 'ravi.thakur@nectarenviro.com',
    password: P,
    name: 'Ravi Thakur',
    role: 'employee',
    siteId: 's-mee',
    employeeId: 'emp0146',
    visibleOnLogin: true,
    active: true,
  },
  // Hidden / legacy
  {
    email: 'asha.patil@nectarenviro.com',
    password: P,
    name: 'Shilpa Hotkar',
    role: 'employee',
    siteId: 's-etp',
    employeeId: 'emp0126',
    visibleOnLogin: false,
    active: true,
  },
  {
    email: 'priyanka.sharma@nectarenviro.com',
    password: P,
    name: 'Swati Ingle',
    role: 'hr',
    employeeId: 'emp0147',
    visibleOnLogin: false,
    active: true,
  },
  {
    email: 'site@nectarenviro.com',
    password: P,
    name: 'Legacy Site Lead',
    role: 'site_incharge',
    siteId: 's-etp',
    employeeId: 'emp0123',
    visibleOnLogin: false,
    active: true,
  },
  {
    email: 'safety@nectarenviro.com',
    password: P,
    name: 'Safety In-Charge',
    role: 'safety_incharge',
    siteId: 's-etp',
    visibleOnLogin: false,
    active: true,
  },
  // E-Permit Heads of Department + deputies
  ...hodUsersSeed,
];
