/**
 * Shared inline-style objects, hoisted verbatim from components (values unchanged).
 * Generated by the Phase 1 refactor — edit freely, but keep values identical
 * unless you intend a visual change.
 */
import type { CSSProperties } from "react";
import { nectarColors } from "@/lib/theme";

export const sSerifText18Mb12: CSSProperties = {
  fontFamily: "var(--font-fraunces), Georgia, serif",
  fontSize: 18,
  marginBottom: 12,
};

export const sSerifText16SemiboldInkM0: CSSProperties = {
  margin: 0,
  fontSize: 16,
  fontWeight: 600,
  fontFamily: "var(--font-fraunces), Georgia, serif",
  color: nectarColors.ink,
};

export const rowWrapGap1BgR8: CSSProperties = {
  display: "flex",
  flexWrap: "wrap",
  gap: 1,
  background: "rgba(28, 68, 99, 0.06)",
  borderRadius: 8,
  overflow: "hidden",
};

export const gridGap16: CSSProperties = {
  display: "grid",
  gridTemplateColumns: "1fr 1fr",
  gap: 16,
};

export const sWhitePadR10Border: CSSProperties = {
  background: nectarColors.white,
  padding: 20,
  borderRadius: 10,
  border: "1px solid rgba(28, 68, 99, 0.08)",
};

export const sSerifText18InkMb4: CSSProperties = {
  fontFamily: "var(--font-fraunces), Georgia, serif",
  fontSize: 18,
  color: nectarColors.ink,
  marginBottom: 4,
};

export const sSerifText18InkMb12: CSSProperties = {
  fontFamily: "var(--font-fraunces), Georgia, serif",
  fontSize: 18,
  marginBottom: 12,
  color: nectarColors.ink,
};

export const sWhitePadR12BorderShadow: CSSProperties = {
  background: nectarColors.white,
  borderRadius: 12,
  padding: 20,
  border: "1px solid #E2E8F0",
  boxShadow: "0 1px 3px rgba(0,0,0,0.04)",
};

export const sSerifText18Ink: CSSProperties = {
  fontFamily: "var(--font-fraunces), Georgia, serif",
  fontSize: 18,
  color: nectarColors.ink,
};

export const sSerifText22: CSSProperties = {
  fontFamily: "var(--font-fraunces), Georgia, serif",
  fontSize: 22,
};

export const rowBetweenWrapGap12: CSSProperties = {
  display: "flex",
  justifyContent: "space-between",
  gap: 12,
  flexWrap: "wrap",
};

export const sText11SemiboldColorBgR6Border: CSSProperties = {
  borderRadius: 6,
  fontWeight: 600,
  fontSize: 11,
  background: "#FFFBEB",
  color: "#D97706",
  border: "1px dashed #F59E0B",
};

export const sSerifText22Ink: CSSProperties = {
  fontFamily: "var(--font-fraunces), Georgia, serif",
  fontSize: 22,
  color: nectarColors.ink,
};

export const sSerifText26Ink: CSSProperties = {
  fontFamily: "var(--font-fraunces), Georgia, serif",
  fontSize: 26,
  color: nectarColors.ink,
};

export const gridGap162: CSSProperties = {
  display: "grid",
  gridTemplateColumns: "1.2fr 1fr",
  gap: 16,
};

export const rowCenterBetweenWrapGap12: CSSProperties = {
  display: "flex",
  justifyContent: "space-between",
  gap: 12,
  flexWrap: "wrap",
  alignItems: "center",
};

export const sWhiteR14BorderShadow: CSSProperties = {
  background: "#FFFFFF",
  borderRadius: 14,
  border: "1px solid rgba(28, 68, 99, 0.08)",
  boxShadow: "0 2px 10px rgba(11, 26, 36, 0.03)",
  overflow: "hidden",
};

export const sSerifText18InkMb122: CSSProperties = {
  fontFamily: "var(--font-fraunces), Georgia, serif",
  fontSize: 18,
  color: nectarColors.ink,
  marginBottom: 12,
};

export const rowCenterBetween2: CSSProperties = {
  display: "flex",
  justifyContent: "space-between",
  alignItems: "center",
};

export const sWhitePadR10: CSSProperties = {
  background: nectarColors.white,
  padding: 20,
  borderRadius: 10,
};

export const sWhitePad: CSSProperties = {
  background: nectarColors.white,
  padding: 20,
  height: "100%",
};

export const rowBetween: CSSProperties = {
  display: "flex",
  justifyContent: "space-between",
  alignItems: "baseline",
};

export const sWhitePad2: CSSProperties = {
  background: nectarColors.white,
  padding: "14px 16px",
};
